### ISSUE TITLE
Timeout on VM

### ISSUE THREAD

**Issue by ybtag** [bkerler/edl#107]
I keep getting a USB timeout on my Ubuntu VM. How can I adjust the timeout?

Reading from physical partition 0, sector 0, sectors 32
Progress: |█████████████-------------------------------------| 26.0% CompleteTraceback (most recent call last):
  File "./edl.py", line 419, in <module>
    main()
  File "./edl.py", line 197, in main
    data = fh.cmd_read_buffer(args.lun, 0, 0x4000 // cfg.SECTOR_SIZE_IN_BYTES)
  File "/home/yitzchok/edlandy/Library/firehose.py", line 249, in cmd_read_buffer
    tmp=self.cdc.read(self.cfg.MaxPayloadSizeToTargetInBytes)
  File "/home/yitzchok/edlandy/Library/usb.py", line 67, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "/usr/local/lib/python3.6/dist-packages/usb/core.py", line 1024, in read
    self.__get_timeout(timeout))
  File "/usr/local/lib/python3.6/dist-packages/usb/backend/libusb1.py", line 851, in bulk_read
    timeout)
  File "/usr/local/lib/python3.6/dist-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/local/lib/python3.6/dist-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out

**Comment by bkerler** [comment]
Hi, this problem should be solved in the upcoming commit

**Comment by bkerler** [comment]
Please try commit 5e05d08
