### ISSUE TITLE
Windows 10 compatibility issues

### ISSUE THREAD

**Issue by thesoundofom** [bkerler/edl#13]
Current build environment: Python 3.7.5, Visual C++ Studio 2019 Community Edition with Microsoft Visual C++ 14.2. Was necessary to install python -m pip install --upgrade setuptools before doing python -m pip install -r requirements.txt

Currently not working, neither with Qualcomm HS-USB QDLoader 9008 + libusb-win32 (nor with Zadig 2.4).

Traceback:

PS E:\personal\tools\edl\edl-master\edl-master> python edl.py printgpt --memory=UFS --debugmode

Library.usblib - connect:0x80000
Library.firehose - Chip serial num: ********** (0x********)
Library.usblib - connect:0x80000
Traceback (most recent call last):
  File "E:\personal\tools\edl\edl-master\edl-master\Library\usblib.py", line 172, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "C:\Users\csorgi\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\core.py", line 988, in read
    self.__get_timeout(timeout))
  File "C:\Users\csorgi\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\backend\libusb0.py", line 542, in bulk_read
    timeout)
  File "C:\Users\csorgi\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\backend\libusb0.py", line 627, in __read
    timeout
  File "C:\Users\csorgi\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\backend\libusb0.py", line 431, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "edl.py", line 1712, in <module>
    main()
  File "edl.py", line 411, in main
    handle_firehose(args, cdc, sahara, verbose)
  File "edl.py", line 1145, in handle_firehose
    supported_functions = fh.connect(0)
  File "E:\personal\tools\edl\edl-master\edl-master\Library\firehose.py", line 513, in connect
    data=self.cdc.read() #logbuf
  File "E:\personal\tools\edl\edl-master\edl-master\Library\usblib.py", line 174, in read
    if "timed out" in e.strerror:
TypeError: a bytes-like object is required, not 'str'

**Comment by bkerler** [comment]
It seems you are using a outdated version. The issue should be fixes in the current version :)
