### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode

### ISSUE THREAD

**Issue by ligteltelecom** [bkerler/edl#162]
c:\edl>python "c:\edl\edl.py"
Qualcomm Sahara / Firehose Client V3.52 (c) B.Kerler 2018-2021.
Traceback (most recent call last):
  File "c:\edl\edl.py", line 359, in <module>
    base.run()
  File "c:\edl\edl.py", line 218, in run
    proper_driver = console_cmd(r'reg query HKLM\HARDWARE\DEVICEMAP\SERIALCOMM')
  File "c:\edl\edl.py", line 153, in console_cmd
    output = read.stdout.read().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 17: invalid continuation byte

c:\edl>

**Comment by ligteltelecom** [comment]
Hi 
Can you help me with this issue?

**Comment by bkerler** [comment]
I will have a closer look.
