### ISSUE TITLE
new commit error

### ISSUE THREAD

**Issue by deyvs02** [bkerler/edl#173]
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
Traceback (most recent call last):
  File "C:\edl\MTK\SP_Flash_Tool\Adb\Python39\Doc\log\edl", line 362, in <module>
    base.run()
  File "C:\edl\MTK\SP_Flash_Tool\Adb\Python39\Doc\log\edl", line 241, in run
    self.cdc = UsbClass(portconfig=portconfig, loglevel=self.__logger.level)
  File "C:\edl\MTK\SP_Flash_Tool\Adb\Python39\Doc\log\edlclient\Library\usblib.py", line 105, in __init__
    if calcsize("P") * 8 == 64:
NameError: name 'calcsize' is not defined

**Comment by deyvs02** [comment]
Work
