### ISSUE TITLE
Zadig still required?

### ISSUE THREAD

**Issue by ybtag** [bkerler/edl#187]
According to the new README.md, it seems that Zadig is no longer required on Windows, which would be great for compatibility with other flashing programs.

Accordingly, I installed UsbDk on a Windows machine without Zadig. The device shows with "UsbDkController -n". But when I run edl, I still get this error:

main - [LIB]: ←[33mPlease first install libusb_win32 driver from Zadig←[0m
main - Trying with no loader given ...
main - Waiting for the device
Traceback (most recent call last):
  File "edl", line 367, in <module>
    base.run()
  File "edl", line 257, in run
    mode, resp = self.doconnect(loop, mode, resp)
  File "edl", line 179, in doconnect
    self.cdc.connected = self.cdc.connect()
  File "C:\Users\Yitzchok\newedlbk\edlclient\Library\usblib.py", line 272, in connect
    self.configuration = self.device.get_active_configuration()
  File "C:\Users\Yitzchok\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\core.py", line 909, in get_active_configuration
    return self._ctx.get_active_configuration(self)
  File "C:\Users\Yitzchok\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\Yitzchok\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\core.py", line 247, in get_active_configuration
    self.managed_open()
  File "C:\Users\Yitzchok\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\Yitzchok\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "C:\Users\Yitzchok\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "C:\Users\Yitzchok\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "C:\Users\Yitzchok\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\backend\libusb1.py", line 600, in _check
    raise NotImplementedError(_strerror(ret))
NotImplementedError: Operation not supported or unimplemented on this platform

Is Zadig really still required?

**Comment by ybtag** [comment]
I upgraded to Python 2.9. Now I no longer get the error mentioned above. Instead, edl waits for the device for a long time, then Windows pops up with a message that my device is not recognized.

**Comment by bkerler** [comment]
I will review edl on windows very soon.

**Comment by bkerler** [comment]
continuing on #160
