### ISSUE TITLE
Need your help to recover realme xt

### ISSUE THREAD

**Issue by rohitharkhani** [bkerler/edl#22]
Hi 
By mistake, I have locked boot loader of my RMX1921 with the custom ROM. So now I am not able to boot into fastboot nor it. Also because of the custom ROM and TWRP device doesn't boot into normal/recovery mode.

I was trying to perform OEM unlock using this tool. 

I have download .[ofp fle ](http://www.mediafire.com/file/v23hyp0nox5dfac/RMX1921EX_11_C.01_200112_e008b81b_GsmMafia.Com.zip/file) ref [page](https://www.gsmmafia.com/realme-xt-rmx1921-flash-file/) 

trying to perform some unlock but Sahara is not able to connect to the device 

`python3 edl/edl.py oemunlock --memory=ufs --loader=firehosefiles/prog_firehose_ddr.elf --debugmode`

the device is detected as `us 001 Device 090: ID 05c6:9008 Qualcomm, Inc. Gobi Wireless Modem (QDL mode)`

`Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2020.
__main__ - Using loader firehosefiles/prog_firehose_ddr.elf ...
__main__ - Waiting for the device
__main__ - Ohuh
Library.usblib - Couldn't detect the device. Is it connected ?
.Library.usblib - Couldn't detect the device. Is it connected ?
.Library.usblib -   CONFIGURATION 1: 160 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x20 (32 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :   0x50 (160 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0x42
     bInterfaceProtocol :    0x3
     iInterface         :    0x4 9008
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x1
__main__ - Device detected :)
Library.usblib - connect:0x80000
Library.usblib - Timed out
Library.usblib - b''
Library.usblib - TX: <?xml version="1.0" ?><data><nop /></data>
Library.usblib - connect:0x80000
Library.usblib - Timed out
Library.usblib - b''
Library.usblib - TX: 

Library.usblib - get_rsp:0x80000
Library.usblib - Timed out
Library.usblib - b''
Library.usblib - connect:0x80000
Library.usblib - Timed out
Library.usblib - b''
Library.usblib - TX: <?xml version="1.0" ?><data><nop /></data>
Library.usblib - connect:0x80000
Library.usblib - Timed out
Library.usblib - b''
Library.usblib - TX: 

Library.usblib - get_rsp:0x80000
Library.usblib - Timed out
Library.usblib - b''
Traceback (most recent call last):
  File "edl/edl.py", line 437, in doconnect
    mode, resp = sahara.connect()
  File "/home/rohit/Android/Sdk/platform-tools/realme/edl/Library/sahara.py", line 332, in connect
    cmd, pkt = self.get_rsp()
  File "/home/rohit/Android/Sdk/platform-tools/realme/edl/Library/sahara.py", line 260, in get_rsp
    pkt = read_object(v[0:0x2*0x4], self.pkt_cmd_hdr)
  File "/home/rohit/Android/Sdk/platform-tools/realme/edl/Library/utils.py", line 264, in read_object
    obj[name] = struct.unpack(stype, data[pos:pos+struct.calcsize(stype)])[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "edl/edl.py", line 1744, in <module>
    main()
  File "edl/edl.py", line 377, in main
    mode, resp = doconnect(cdc, loop, mode, resp, sahara)
  File "edl/edl.py", line 442, in doconnect
    mode, resp = sahara.connect()
  File "/home/rohit/Android/Sdk/platform-tools/realme/edl/Library/sahara.py", line 332, in connect
    cmd, pkt = self.get_rsp()
  File "/home/rohit/Android/Sdk/platform-tools/realme/edl/Library/sahara.py", line 260, in get_rsp
    pkt = read_object(v[0:0x2*0x4], self.pkt_cmd_hdr)
  File "/home/rohit/Android/Sdk/platform-tools/realme/edl/Library/utils.py", line 264, in read_object
    obj[name] = struct.unpack(stype, data[pos:pos+struct.calcsize(stype)])[0]
struct.error: unpack requires a buffer of 4 bytes
`

**Comment by rohitharkhani** [comment]
Apologise I was not able to find out any other way to connect with you apart from issue. can you please help me what's wrong going on or any error in my command?
