### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'pycryptodome' distribution was not found and is required by edlclient

### ISSUE THREAD

**Issue by khperez** [bkerler/edl#228]
MacOS version: 12.1
Python Version: 3.9.10

```
$ edl
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycryptodome' distribution was not found and is required by edlclient
```

Tried to make sure it was installed for python 3:
```
$ python3 -m pip install pycryptodome
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pycryptodome in /opt/homebrew/lib/python3.9/site-packages/pycryptodome-3.14.0-py3.9-macosx-12-arm64.egg (3.14.0)
```

**Comment by bkerler** [comment]
make sure that the python you are running is the same that calls the edl script, looks like a python misconfiguration.
Try "sudo pip3 install pycryptodome" instead.
