### ISSUE TITLE
Open-Q 820 MSM8996 support

### ISSUE THREAD

**Issue by rabits** [bkerler/edl#232]
Hello dear developer,

Trying to use EDL to get GPT from my [Open-Q 820 devboard](https://www.lantronix.com/products/open-q-820-usom-development-kit/) ([uSoM 820](https://www.lantronix.com/products/open-q-820-usom/)) - but getting the weird issues:

* Reading gpt, but got stuck right on `firehose - Trying to read first storage sector...` (debugmode log: [printgpt.log.xz.zip](https://github.com/bkerler/edl/files/8065492/printgpt.log.xz.zip) ):
   <details>
      <summary>Command and log</summary>
      
      $ edl --memory ufs --loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin printgpt
      Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
      main - Using loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin ...
      main - Waiting for the device
      main - Device detected :)
      sahara - Protocol version: 2.1
      main - Mode detected: sahara
      sahara -
      ------------------------
      HWID:              0x0003e0e100000000 (MSM_ID:0x0003e0e1,OEM_ID:0x0000,MODEL_ID:0x0000)
      Unknown CPU, please send log as issue to https://github.com/bkerler/edl
      PK_HASH:           0x7be49b72f9e4337223ccb84d6eccca4e61ce16e3602ac2008cb18b75babe6d09
      Serial:            0x2b5f6219

      sahara - Protocol version: 2.1
      sahara - Uploading loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin ...
      sahara - 64-Bit mode detected.
      sahara - Firehose mode detected, uploading...
      sahara - Loader successfully uploaded.
      main - Trying to connect to firehose loader ...
      firehose - Binary build date: Jan 12 2016 @ 17:39:26
      firehose - Chip serial num: 727671321 (0x2b5f6219)
      firehose - Supported Functions: program configure nop firmwarewrite patch setbootablestoragedrive ufs emmc readIMEI writeIMEI simlock power benchmark read eMMCinfo getstorageinfo getsha256digest erase peek poke
      firehose - TargetName=MSM8996
      firehose - MemoryName=UFS
      firehose - Version=2
      firehose - Trying to read first storage sector...

   </details>
* Dumping the flash, but stuck again (debugmode log: [rl_dumps.log.xz.zip](https://github.com/bkerler/edl/files/8066209/rl_dumps.log.xz.zip)):
   <details>
      <summary>Command and log</summary>

      $ edl --memory ufs --loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin --lun 0 --skip userdata rl dumps
      Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
      main - Using loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin ...
      main - Waiting for the device
      main - Device detected :)
      sahara - Protocol version: 2.1
      main - Mode detected: sahara
      sahara -
      ------------------------
      HWID:              0x0003e0e100000000 (MSM_ID:0x0003e0e1,OEM_ID:0x0000,MODEL_ID:0x0000)
      Unknown CPU, please send log as issue to https://github.com/bkerler/edl
      PK_HASH:           0x7be49b72f9e4337223ccb84d6eccca4e61ce16e3602ac2008cb18b75babe6d09
      Serial:            0x2b5f6219

      sahara - Protocol version: 2.1
      sahara - Uploading loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin ...
      sahara - 64-Bit mode detected.
      sahara - Firehose mode detected, uploading...
      sahara - Loader successfully uploaded.
      main - Trying to connect to firehose loader ...
      firehose - Binary build date: Jan 12 2016 @ 17:39:26
      firehose - Chip serial num: 727671321 (0x2b5f6219)
      firehose - Supported Functions: program configure nop firmwarewrite patch setbootablestoragedrive ufs emmc readIMEI writeIMEI simlock power benchmark read eMMCinfo getstorageinfo getsha256digest erase peek poke
      firehose - TargetName=MSM8996
      firehose - MemoryName=UFS
      firehose - Version=2
      firehose - Trying to read first storage sector...

   </details>

Not sure I use the right firehose, but I tried the others for MSM8996 I found for [dragonboard 820c](https://www.96boards.org/documentation/consumer/dragonboard/dragonboard820c/installation/board-recovery.md.html#flashing-the-device) (since the devboard is not secured it should work), but got the trace - looks like edl don't like to get the logs on configure:
<details>
   <summary>Command and log</summary>

   $ edl --memory=ufs --loader ../qdl/dragonboard-820c-bootloader-ufs-aosp-110/prog_ufs_firehose_8996_ddr.elf printgpt
   Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
   main - Using loader ../qdl/dragonboard-820c-bootloader-ufs-aosp-110/prog_ufs_firehose_8996_ddr.elf ...
   main - Waiting for the device
   main - Device detected :)
   sahara - Protocol version: 2.1
   main - Mode detected: sahara
   sahara -
   ------------------------
   HWID:              0x0003e0e100000000 (MSM_ID:0x0003e0e1,OEM_ID:0x0000,MODEL_ID:0x0000)
   Unknown CPU, please send log as issue to https://github.com/bkerler/edl
   PK_HASH:           0x7be49b72f9e4337223ccb84d6eccca4e61ce16e3602ac2008cb18b75babe6d09
   Serial:            0x2b5f6219

   sahara - Protocol version: 2.1
   sahara - Uploading loader ../qdl/dragonboard-820c-bootloader-ufs-aosp-110/prog_ufs_firehose_8996_ddr.elf ...
   sahara - 64-Bit mode detected.
   sahara - Firehose mode detected, uploading...
   sahara - Loader successfully uploaded.
   main - Trying to connect to firehose loader ...
   Traceback (most recent call last):
     File "/usr/local/bin/edl", line 4, in <module>
       __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
     File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 650, in run_script
       self.require(requires)[0].run_script(script_name, ns)
     File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
       exec(code, namespace, namespace)
     File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 380, in <module>
       base.run()
     File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 375, in run
       if fh.connect(sahara):
     File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose_client.py", line 109, in connect
       if self.firehose.configure(0):
     File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose.py", line 851, in configure
       if "MemoryName" in rsp.data:
   TypeError: a bytes-like object is required, not 'str'

</details>

I think it's related to the additional logs it's producing and configure doesn't expect that. If I wrap it into try/catch with print out the rsp.data I see next:
```
firehose - [LIB]: !DEBUG! rsp.data: 'bytearray(b'<?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<log value="Binary build date: Jul 15 2016 @ 04:52:20"/>\n</data><?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<log value="Chip serial num: 727671321 (0x2b5f6219)"/>\n</data><?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<log value="Supported Functions: program configure nop firmwarewrite patch setbootablestoragedrive ufs emmc power benchmark read getstorageinfo getsha256digest erase peek poke "/>\n</data>')'
```

To be fair the QFIL 2.0.3.5 (QPST 2.7.496) also not working well for me to get the partition table, so maybe you can see something out right away and I'm continue to check the ways on my side. If you want me to do some debugging or provide additional info - feel free to ask.

Thank you

**Comment by rabits** [comment]
Tried with `--skipstorageinit` and I'm able to dump PBL (with non critical errors):
<details>
    <summary>Command and log</summary>

    $ edl --skipstorageinit --loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin pbl out.pbl
    Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
    main - Using loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin ...
    main - Waiting for the device
    main - Device detected :)
    sahara - Protocol version: 2.1
    main - Mode detected: sahara
    sahara -
    ------------------------
    HWID:              0x0003e0e100000000 (MSM_ID:0x0003e0e1,OEM_ID:0x0000,MODEL_ID:0x0000)
    Unknown CPU, please send log as issue to https://github.com/bkerler/edl
    PK_HASH:           0x7be49b72f9e4337223ccb84d6eccca4e61ce16e3602ac2008cb18b75babe6d09
    Serial:            0x2b5f6219

    sahara - Protocol version: 2.1
    sahara - Uploading loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin ...
    sahara - 64-Bit mode detected.
    sahara - Firehose mode detected, uploading...
    sahara - Loader successfully uploaded.
    main - Trying to connect to firehose loader ...
    firehose - Binary build date: Jan 12 2016 @ 17:39:26
    firehose - Chip serial num: 727671321 (0x2b5f6219)
    firehose - Supported Functions: program configure nop firmwarewrite patch setbootablestoragedrive ufs emmc readIMEI writeIMEI simlock power benchmark read eMMCinfo getstorageinfo getsha256digest erase peek poke
    firehose_client
    firehose_client - [LIB]: No --memory option set, we assume "UFS" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
    firehose - TargetName=MSM8996
    firehose - MemoryName=UFS
    firehose - Version=2
    firehose - Trying to read first storage sector...
    firehose - Running configure...
    firehose - {'UFS fInitialized': '0x1', 'UFS Current LUN Number: ': ' 0xd0', 'UFS Total Active LU': '0x6', 'UFS wManufacturerID': '0x198', 'UFS Boot Partition Enabled': '0x1', 'UFS Raw Device Capacity: ': ' 0x3b9e000', 'UFS Min Block Size': '0x8', 'UFS Erase Block Size': '0x2000', 'UFS Allocation Unit Size': '0x1', 'UFS RPMB ReadWrite Size: ': ' 0x40', 'UFS Number of Allocation Uint for This LU': '0x0', 'UFS Logical Block Size': '0x0', 'UFS Provisioning Type': '0x0', 'UFS LU Write Protect': '0x0', 'UFS Boot LUN ID: ': ' 0x0', 'UFS Memory Type': '0x0', 'UFS LU Total Blocks': '0x0', 'UFS Supported Memory Types': '0x801f', 'UFS dEnhanced1MaxNAllocU': '0x1dcf', 'UFS wEnhanced1CapAdjFac': '0x200', 'UFS dEnhanced2MaxNAllocU: ': ' 0x20', 'UFS wEnhanced2CapAdjFac': '0x200', 'UFS dEnhanced3MaxNAllocU': '0x0', 'UFS wEnhanced3CapAdjFac': '0x0', 'UFS dEnhanced4MaxNAllocU': '0x0', 'UFS wEnhanced4CapAdjFac': '0x0', 'UFS LUN Enable Bitmask': '0x3f', 'UFS Logical Block Count': '0x0', 'UFS bConfigDescrLock': '0x0', 'UFS iManufacturerName String Index': '0x1', 'UFS iProductName String Index': '0x2', 'UFS iSerialNumber String Index': '0x3', 'UFS iOemID String Index': '0x4', 'UFS Inquiry Command Output': 'TOSHIBA THGAF4G8N2LBAIRB0100 '}
    firehose - {'UFS fInitialized': '0x1', 'UFS Current LUN Number: ': ' 0xd0', 'UFS Total Active LU': '0x6', 'UFS wManufacturerID': '0x198', 'UFS Boot Partition Enabled': '0x1', 'UFS Raw Device Capacity: ': ' 0x3b9e000', 'UFS Min Block Size': '0x8', 'UFS Erase Block Size': '0x2000', 'UFS Allocation Unit Size': '0x1', 'UFS RPMB ReadWrite Size: ': ' 0x40', 'UFS Number of Allocation Uint for This LU': '0x0', 'UFS Logical Block Size': '0x0', 'UFS Provisioning Type': '0x0', 'UFS LU Write Protect': '0x0', 'UFS Boot LUN ID: ': ' 0x0', 'UFS Memory Type': '0x0', 'UFS LU Total Blocks': '0x0', 'UFS Supported Memory Types': '0x801f', 'UFS dEnhanced1MaxNAllocU': '0x1dcf', 'UFS wEnhanced1CapAdjFac': '0x200', 'UFS dEnhanced2MaxNAllocU: ': ' 0x20', 'UFS wEnhanced2CapAdjFac': '0x200', 'UFS dEnhanced3MaxNAllocU': '0x0', 'UFS wEnhanced3CapAdjFac': '0x0', 'UFS dEnhanced4MaxNAllocU': '0x0', 'UFS wEnhanced4CapAdjFac': '0x0', 'UFS LUN Enable Bitmask': '0x3f', 'UFS Logical Block Count': '0x0', 'UFS bConfigDescrLock': '0x0', 'UFS iManufacturerName String Index': '0x1', 'UFS iProductName String Index': '0x2', 'UFS iSerialNumber String Index': '0x3', 'UFS iOemID String Index': '0x4', 'UFS Inquiry Command Output': 'TOSHIBA THGAF4G8N2LBAIRB0100 '}
    firehose - 0x1
    firehose_client - Supported functions:
    -----------------
    program,configure,nop,firmwarewrite,patch,setbootablestoragedrive,ufs,emmc,readIMEI,writeIMEI,simlock,power,benchmark,read,eMMCinfo,getstorageinfo,getsha256digest,erase,peek,poke
    firehose
    firehose - [LIB]: Storage read failed at sector 0 length 2 errno=-1
    firehose
    firehose - [LIB]: ERROR 4: Line 411: STORAGE_READ_FAILURE
    firehose
    firehose - [LIB]: Read failed at sector 0
    firehose
    firehose - [LIB]: ERROR 4: Line 2264: STORAGE_READ_FAILURE
    firehose
    firehose - [LIB]: Finished reading from sector address 0 to 2
    firehose - Peek: Address(0x100000),Size(0x1ffb0)
    Progress: |██████████████████████████████████████████████████| 100.0% Complete
    firehose - Bytes from 0x100000, bytes read 0x1ffb0, written to out.pbl.
    Dumped pbl at offset 0x100000 as out.pbl.

</details>

But can't work with UFS (debugmode log: [skipstorageinit_rl_dumps.log.xz.zip](https://github.com/bkerler/edl/files/8066510/skipstorageinit_rl_dumps.log.xz.zip)):
<details>
    <summary>Command and log</summary>

    $ edl rl dumps --memory UFS --skipstorageinit --loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin --genxml
    Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
    main - Using loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin ...
    main - Waiting for the device
    main - Device detected :)
    sahara - Protocol version: 2.1
    main - Mode detected: sahara
    sahara -
    ------------------------
    HWID:              0x0003e0e100000000 (MSM_ID:0x0003e0e1,OEM_ID:0x0000,MODEL_ID:0x0000)
    Unknown CPU, please send log as issue to https://github.com/bkerler/edl
    PK_HASH:           0x7be49b72f9e4337223ccb84d6eccca4e61ce16e3602ac2008cb18b75babe6d09
    Serial:            0x2b5f6219

    sahara - Protocol version: 2.1
    sahara - Uploading loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin ...
    sahara - 64-Bit mode detected.
    sahara - Firehose mode detected, uploading...
    sahara - Loader successfully uploaded.
    main - Trying to connect to firehose loader ...
    firehose - Binary build date: Jan 12 2016 @ 17:39:26
    firehose - Chip serial num: 727671321 (0x2b5f6219)
    firehose - Supported Functions: program configure nop firmwarewrite patch setbootablestoragedrive ufs emmc readIMEI writeIMEI simlock power benchmark read eMMCinfo getstorageinfo getsha256digest erase peek poke
    firehose - TargetName=MSM8996
    firehose - MemoryName=UFS
    firehose - Version=2
    firehose - Trying to read first storage sector...
    firehose - Running configure...
    firehose - {'UFS fInitialized': '0x1', 'UFS Current LUN Number: ': ' 0xd0', 'UFS Total Active LU': '0x6', 'UFS wManufacturerID': '0x198', 'UFS Boot Partition Enabled': '0x1', 'UFS Raw Device Capacity: ': ' 0x3b9e000', 'UFS Min Block Size': '0x8', 'UFS Erase Block Size': '0x2000', 'UFS Allocation Unit Size': '0x1', 'UFS RPMB ReadWrite Size: ': ' 0x40', 'UFS Number of Allocation Uint for This LU': '0x0', 'UFS Logical Block Size': '0x0', 'UFS Provisioning Type': '0x0', 'UFS LU Write Protect': '0x0', 'UFS Boot LUN ID: ': ' 0x0', 'UFS Memory Type': '0x0', 'UFS LU Total Blocks': '0x0', 'UFS Supported Memory Types': '0x801f', 'UFS dEnhanced1MaxNAllocU': '0x1dcf', 'UFS wEnhanced1CapAdjFac': '0x200', 'UFS dEnhanced2MaxNAllocU: ': ' 0x20', 'UFS wEnhanced2CapAdjFac': '0x200', 'UFS dEnhanced3MaxNAllocU': '0x0', 'UFS wEnhanced3CapAdjFac': '0x0', 'UFS dEnhanced4MaxNAllocU': '0x0', 'UFS wEnhanced4CapAdjFac': '0x0', 'UFS LUN Enable Bitmask': '0x3f', 'UFS Logical Block Count': '0x0', 'UFS bConfigDescrLock': '0x0', 'UFS iManufacturerName String Index': '0x1', 'UFS iProductName String Index': '0x2', 'UFS iSerialNumber String Index': '0x3', 'UFS iOemID String Index': '0x4', 'UFS Inquiry Command Output': 'TOSHIBA THGAF4G8N2LBAIRB0100 '}
    firehose - {'UFS fInitialized': '0x1', 'UFS Current LUN Number: ': ' 0xd0', 'UFS Total Active LU': '0x6', 'UFS wManufacturerID': '0x198', 'UFS Boot Partition Enabled': '0x1', 'UFS Raw Device Capacity: ': ' 0x3b9e000', 'UFS Min Block Size': '0x8', 'UFS Erase Block Size': '0x2000', 'UFS Allocation Unit Size': '0x1', 'UFS RPMB ReadWrite Size: ': ' 0x40', 'UFS Number of Allocation Uint for This LU': '0x0', 'UFS Logical Block Size': '0x0', 'UFS Provisioning Type': '0x0', 'UFS LU Write Protect': '0x0', 'UFS Boot LUN ID: ': ' 0x0', 'UFS Memory Type': '0x0', 'UFS LU Total Blocks': '0x0', 'UFS Supported Memory Types': '0x801f', 'UFS dEnhanced1MaxNAllocU': '0x1dcf', 'UFS wEnhanced1CapAdjFac': '0x200', 'UFS dEnhanced2MaxNAllocU: ': ' 0x20', 'UFS wEnhanced2CapAdjFac': '0x200', 'UFS dEnhanced3MaxNAllocU': '0x0', 'UFS wEnhanced3CapAdjFac': '0x0', 'UFS dEnhanced4MaxNAllocU': '0x0', 'UFS wEnhanced4CapAdjFac': '0x0', 'UFS LUN Enable Bitmask': '0x3f', 'UFS Logical Block Count': '0x0', 'UFS bConfigDescrLock': '0x0', 'UFS iManufacturerName String Index': '0x1', 'UFS iProductName String Index': '0x2', 'UFS iSerialNumber String Index': '0x3', 'UFS iOemID String Index': '0x4', 'UFS Inquiry Command Output': 'TOSHIBA THGAF4G8N2LBAIRB0100 '}
    firehose - 0x1
    firehose_client - Supported functions:
    -----------------
    program,configure,nop,firmwarewrite,patch,setbootablestoragedrive,ufs,emmc,readIMEI,writeIMEI,simlock,power,benchmark,read,eMMCinfo,getstorageinfo,getsha256digest,erase,peek,poke
    firehose
    firehose - [LIB]: Storage read failed at sector 0 length 2 errno=-1
    firehose
    firehose - [LIB]: ERROR 4: Line 411: STORAGE_READ_FAILURE
    firehose
    firehose - [LIB]: Read failed at sector 0
    firehose
    firehose - [LIB]: ERROR 4: Line 2264: STORAGE_READ_FAILURE
    firehose
    firehose - [LIB]: Finished reading from sector address 0 to 2
    firehose
    firehose - [LIB]: Storage read failed at sector 0 length 2 errno=-1
    firehose
    firehose - [LIB]: ERROR 4: Line 411: STORAGE_READ_FAILURE
    firehose
    firehose - [LIB]: Read failed at sector 0
    firehose
    firehose - [LIB]: ERROR 4: Line 2264: STORAGE_READ_FAILURE
    firehose
    firehose - [LIB]: Finished reading from sector address 0 to 2

</details>

**Comment by rabits** [comment]
Actually looks like I found it - `--skipresponse` allows me to get the proper response from the devboard!
```
$ edl printgpt --lun 4 --memory UFS --skipresponse --loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader build/lib/Loaders/qualcomm/model_generic/msm8996/0000000000000000_b53fb23d1953decb_fhprg_peek.bin ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - fh.attrs.Verbose is set to 0
firehose - Chip serial num: 727671321 (0x2b5f6219)
firehose - Supported Functions: program configure nop firmwarewrite patch setbootablestoragedrive ufs emmc readIMEI writeIMEI simlock power benchmark read eMMCinfo getstorageinfo getsha256digest e
rase peek poke
firehose - TargetName=MSM8996
firehose - MemoryName=UFS
firehose - Version=2
firehose - Trying to read first storage sector...
firehose - Running configure...
firehose - {'Device Total Logical Blocks': '0x60ac00', 'Device Block Size in Bytes': '0x1000', 'Device Total Physical Paritions': '0x6', 'Device Manufacturer ID': '0x198', 'Device Serial Number':
'0x0', 'UFS fInitialized': '0x1', 'UFS Current LUN Number: ': ' 0xd0', 'UFS Total Active LU': '0x6', 'UFS wManufacturerID': '0x198', 'UFS Boot Partition Enabled': '0x1', 'UFS Raw Device Capacity:
': ' 0x3b9e000', 'UFS Min Block Size': '0x8', 'UFS Erase Block Size': '0x2000', 'UFS Allocation Unit Size': '0x1', 'UFS RPMB ReadWrite Size: ': ' 0x40', 'UFS Number of Allocation Uint for This LU'
: '0x0', 'UFS Logical Block Size': '0x0', 'UFS Provisioning Type': '0x0', 'UFS LU Write Protect': '0x0', 'UFS Boot LUN ID: ': ' 0x0', 'UFS Memory Type': '0x0', 'UFS LU Total Blocks': '0x0', 'UFS S
upported Memory Types': '0x801f', 'UFS dEnhanced1MaxNAllocU': '0x1dcf', 'UFS wEnhanced1CapAdjFac': '0x200', 'UFS dEnhanced2MaxNAllocU: ': ' 0x20', 'UFS wEnhanced2CapAdjFac': '0x200', 'UFS dEnhance
d3MaxNAllocU': '0x0', 'UFS wEnhanced3CapAdjFac': '0x0', 'UFS dEnhanced4MaxNAllocU': '0x0', 'UFS wEnhanced4CapAdjFac': '0x0', 'UFS LUN Enable Bitmask': '0x3f', 'UFS Logical Block Count': '0x0', 'UF
S bConfigDescrLock': '0x0', 'UFS iManufacturerName String Index': '0x1', 'UFS iProductName String Index': '0x2', 'UFS iSerialNumber String Index': '0x3', 'UFS iOemID String Index': '0x4', 'UFS Inq
uiry Command Output': 'TOSHIBA THGAF4G8N2LBAIRB0100 '}
firehose - {'Device Total Logical Blocks': '0x60ac00', 'Device Block Size in Bytes': '0x1000', 'Device Total Physical Paritions': '0x6', 'Device Manufacturer ID': '0x198', 'Device Serial Number':
'0x0', 'UFS fInitialized': '0x1', 'UFS Current LUN Number: ': ' 0xd0', 'UFS Total Active LU': '0x6', 'UFS wManufacturerID': '0x198', 'UFS Boot Partition Enabled': '0x1', 'UFS Raw Device Capacity:
': ' 0x3b9e000', 'UFS Min Block Size': '0x8', 'UFS Erase Block Size': '0x2000', 'UFS Allocation Unit Size': '0x1', 'UFS RPMB ReadWrite Size: ': ' 0x40', 'UFS Number of Allocation Uint for This LU'
: '0x0', 'UFS Logical Block Size': '0x0', 'UFS Provisioning Type': '0x0', 'UFS LU Write Protect': '0x0', 'UFS Boot LUN ID: ': ' 0x0', 'UFS Memory Type': '0x0', 'UFS LU Total Blocks': '0x0', 'UFS S
upported Memory Types': '0x801f', 'UFS dEnhanced1MaxNAllocU': '0x1dcf', 'UFS wEnhanced1CapAdjFac': '0x200', 'UFS dEnhanced2MaxNAllocU: ': ' 0x20', 'UFS wEnhanced2CapAdjFac': '0x200', 'UFS dEnhance
d3MaxNAllocU': '0x0', 'UFS wEnhanced3CapAdjFac': '0x0', 'UFS dEnhanced4MaxNAllocU': '0x0', 'UFS wEnhanced4CapAdjFac': '0x0', 'UFS LUN Enable Bitmask': '0x3f', 'UFS Logical Block Count': '0x0', 'UF
S bConfigDescrLock': '0x0', 'UFS iManufacturerName String Index': '0x1', 'UFS iProductName String Index': '0x2', 'UFS iSerialNumber String Index': '0x3', 'UFS iOemID String Index': '0x4', 'UFS Inq
uiry Command Output': 'TOSHIBA THGAF4G8N2LBAIRB0100 '}
firehose - 0x1
firehose_client - Supported functions:
-----------------
program,configure,nop,firmwarewrite,patch,setbootablestoragedrive,ufs,emmc,readIMEI,writeIMEI,simlock,power,benchmark,read,eMMCinfo,getstorageinfo,getsha256digest,erase,peek,poke

Parsing Lun 4:

GPT Table:
-------------
rpm:                 Offset 0x0000000000006000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID a16bac30-1326-f6ca-8e7c-2faaca32da99, Type 0x98df793, Active False
rpmbak:              Offset 0x0000000000086000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID d8829e88-9b2a-d439-1eac-6609dcf0b2c1, Type 0x98df793, Active False
tz:                  Offset 0x0000000000106000, Length 0x0000000000200000, Flags 0x1000000000000000, UUID 61f7bf05-ab56-e6bc-bb8b-46f59e1ecebc, Type 0xa053aa7f, Active False
tzbak:               Offset 0x0000000000306000, Length 0x0000000000200000, Flags 0x1000000000000000, UUID 8d301041-498d-3b85-1329-80b3cc3d0703, Type 0xa053aa7f, Active False
hyp:                 Offset 0x0000000000506000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID bc3c61eb-95cc-4035-dd09-f92756537f46, Type 0xe1a6a689, Active False
hypbak:              Offset 0x0000000000586000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 5830e1b7-b7ad-0bb4-99f6-d803216013a0, Type 0xe1a6a689, Active False
fsg:                 Offset 0x0000000000606000, Length 0x0000000000200000, Flags 0x1000000000000000, UUID 8cbe317e-dbb3-db04-b7cf-516a5b2ee92a, Type 0x638ff8e2, Active False
sec:                 Offset 0x0000000000806000, Length 0x0000000000004000, Flags 0x1000000000000000, UUID 1548cb91-5b77-48f7-08e7-20e7c6bcadbb, Type 0x303e6ac3, Active False
pmic:                Offset 0x000000000080a000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 53e1ea64-dab9-3542-b7b4-1b935aabb203, Type 0xc00eef24, Active False
pmicbak:             Offset 0x000000000088a000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 8927eacf-79ac-a277-afcd-c5207699b2ec, Type 0xc00eef24, Active False
modem:               Offset 0x000000000090a000, Length 0x0000000005f00000, Flags 0x1000000000000000, UUID 6068c262-35f4-e794-86e3-008b74f19a38, Type EFI_BASIC_DATA, Active False
dsp:                 Offset 0x000000000680a000, Length 0x0000000001000000, Flags 0x1000000000000000, UUID 83ca8a0d-6e04-626f-69f9-cffd8fa2f59e, Type 0x7efe5010, Active False
dip:                 Offset 0x000000000780a000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID e9565799-03db-8a15-5f18-d294b672a990, Type 0x4114b077, Active False
mdtp:                Offset 0x000000000790a000, Length 0x0000000002000000, Flags 0x1000000000000000, UUID c1093cf0-8517-627a-0ba9-3a244fa56a0c, Type 0x3878408a, Active False
aboot:               Offset 0x000000000990a000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID dcd49fc3-dea6-6d20-30a9-069b65d0935d, Type 0x400ffdcd, Active False
abootbak:            Offset 0x0000000009a0a000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID f1491067-00d8-31a0-79c5-d8305c14536b, Type 0x400ffdcd, Active False
boot:                Offset 0x0000000009b0a000, Length 0x0000000004000000, Flags 0x1000000000000000, UUID 0be2bf76-7058-ae79-9edc-e304f3a51bdb, Type 0x20117f86, Active False
system:              Offset 0x000000000db0a000, Length 0x00000000c0000000, Flags 0x1000000000000000, UUID 1533f726-c278-52fe-fa75-9e5dbcc1de5b, Type 0x97d7b011, Active False
recovery:            Offset 0x00000000cdb0a000, Length 0x0000000004000000, Flags 0x1000000000000000, UUID 0cb57bbe-e391-c70f-4ec2-82e5c0c8f41d, Type 0x9d72d4e4, Active False
devinfo:             Offset 0x00000000d1b0a000, Length 0x0000000000001000, Flags 0x1000000000000000, UUID d2457b35-aff9-7485-2b15-af48ae9cc5f6, Type 0x65addcf4, Active False
bluetooth:           Offset 0x00000000d1b0b000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID 57148a79-9018-2330-3796-19ace13d7c5a, Type 0x6cb747f1, Active False
keymaster:           Offset 0x00000000d1c0b000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 4fcd6677-e89a-ec9d-b7a9-627110c320e6, Type 0x4f772165, Active False
keymasterbak:        Offset 0x00000000d1c8b000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID ca67fe2b-5baa-7d25-1ce1-e8814a1dae09, Type 0x4f772165, Active False
cmnlib:              Offset 0x00000000d1d0b000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 087a42b0-6f63-5ddd-b9ca-8ae0e81804c9, Type 0x73471795, Active False
cmnlibbak:           Offset 0x00000000d1d8b000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 29583d61-fffe-bfc5-0b74-81e97a36a8fc, Type 0x73471795, Active False
cmnlib64:            Offset 0x00000000d1e0b000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 251fda90-4a4d-98ae-cff8-af6cd4da0413, Type 0x8ea64893, Active False
cmnlib64bak:         Offset 0x00000000d1e8b000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID f3ef7361-108e-d461-2267-d1ab9dc20a9c, Type 0x8ea64893, Active False
apdp:                Offset 0x00000000d1f0b000, Length 0x0000000000040000, Flags 0x1000000000000000, UUID e25118df-f580-35d6-3f5c-0e2e72498847, Type 0xe6e98da2, Active False
msadp:               Offset 0x00000000d1f4b000, Length 0x0000000000040000, Flags 0x1000000000000000, UUID db3f36c3-18cc-f14c-3a81-0ff9ea5d2535, Type 0xed9e8101, Active False
dpo:                 Offset 0x00000000d1f8b000, Length 0x0000000000001000, Flags 0x1000000000000000, UUID 36ca4436-1a62-e040-fefc-1e1b3a02c3ef, Type 0x11406f35, Active False
splash:              Offset 0x00000000d1f8c000, Length 0x00000000020a4000, Flags 0x1000000000000000, UUID bf92587b-66e1-a141-5c5b-051b03daa7ec, Type 0xad99f201, Active False
sti:                 Offset 0x00000000d4030000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID ab89e120-3cfc-3914-e9ca-2449fe786f6a, Type 0xaa9a5c4c, Active False

Total disk size:0x000000010001c000, sectors:0x000000000010001c
```

So since it works now I think I'm good - closing the ticket)
