### ISSUE TITLE
oppo watch Unknown CPU

### ISSUE THREAD

**Issue by wannaphong** [bkerler/edl#236]
This is my log

```
wannaphong@wannaphong-dell-g3-3500:~/edl$ edl modules oemunlock enable
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2.1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x000520e100510000 (MSM_ID:0x000520e1,OEM_ID:0x0051,MODEL_ID:0x0000)
Unknown CPU, please send log as issue to https://github.com/bkerler/edl
PK_HASH:           0xc8b4fe1cd7221f8816f3f097277e9d7eeed74717761ff773a4267d70041b35d1
Serial:            0x1f57727e

sahara - Detected loader: /usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/../Loaders/oppo/000520e100510000_c8b4fe1cd7221f88_fhprg_peek.bin
sahara - Protocol version: 2.1
sahara - Uploading loader /usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/../Loaders/oppo/000520e100510000_c8b4fe1cd7221f88_fhprg_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: ERROR: Failed to authenticate Digital Signature
wannaphong@wannaphong-dell-g3-3500:~/edl$ edl modules oemunlock enable
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - Nop succeeded.
firehose - 
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "UFS" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: ERROR: Failed to authenticate Digital Signature
wannaphong@wannaphong-dell-g3-3500:~$ edl modules oemunlock enable --memory UFS
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - Nop succeeded.
firehose - 
firehose
firehose - [LIB]: ERROR: Failed to authenticate Digital Signature
wannaphong@wannaphong-dell-g3-3500:~$ sudo adb reboot edl
error: no devices/emulators found
wannaphong@wannaphong-dell-g3-3500:~$ edl modules oemunlock enable
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - Nop succeeded.
firehose - 
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "UFS" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: ERROR: Failed to authenticate Digital Signature
wannaphong@wannaphong-dell-g3-3500:~$ edl modules oemunlock enable --memory NAND
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - ERROR: Failed to authenticate Digital Signature
firehose - Resetting validation state
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 380, in <module>
    base.run()
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 375, in run
    if fh.connect(sahara):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose_client.py", line 109, in connect
    if self.firehose.configure(0):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose.py", line 851, in configure
    if "MemoryName" in rsp.data:
TypeError: a bytes-like object is required, not 'str'
wannaphong@wannaphong-dell-g3-3500:~$ edl modules oemunlock enable --memory NAND
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose
firehose - [LIB]: ERROR: Failed to authenticate Digital Signature
wannaphong@wannaphong-dell-g3-3500:~$ edl modules oemunlock enable --memory spinor
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - ERROR: Failed to authenticate Digital Signature
firehose - Resetting validation state
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 380, in <module>
    base.run()
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 375, in run
    if fh.connect(sahara):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose_client.py", line 109, in connect
    if self.firehose.configure(0):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose.py", line 851, in configure
    if "MemoryName" in rsp.data:
TypeError: a bytes-like object is required, not 'str'
wannaphong@wannaphong-dell-g3-3500:~$ edl modules oemunlock enable
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: ERROR: Failed to authenticate Digital Signature
wannaphong@wannaphong-dell-g3-3500:~$ edl printgpt
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - ERROR: Failed to authenticate Digital Signature
firehose - Resetting validation state
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 380, in <module>
    base.run()
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 375, in run
    if fh.connect(sahara):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose_client.py", line 109, in connect
    if self.firehose.configure(0):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose.py", line 851, in configure
    if "MemoryName" in rsp.data:
TypeError: a bytes-like object is required, not 'str'
wannaphong@wannaphong-dell-g3-3500:~$ edl printgpt --memory=ufs --lun=0
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose
firehose - [LIB]: ERROR: Failed to authenticate Digital Signature
wannaphong@wannaphong-dell-g3-3500:~$ edl secureboot
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - ERROR: Failed to authenticate Digital Signature
firehose - Resetting validation state
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 380, in <module>
    base.run()
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 375, in run
    if fh.connect(sahara):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose_client.py", line 109, in connect
    if self.firehose.configure(0):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose.py", line 851, in configure
    if "MemoryName" in rsp.data:
TypeError: a bytes-like object is required, not 'str'
wannaphong@wannaphong-dell-g3-3500:~$ edl printgpt
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: ERROR: Failed to authenticate Digital Signature
wannaphong@wannaphong-dell-g3-3500:~$ edl modules oemunlock enable
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - ERROR: Failed to authenticate Digital Signature
firehose - Resetting validation state
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 380, in <module>
    base.run()
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 375, in run
    if fh.connect(sahara):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose_client.py", line 109, in connect
    if self.firehose.configure(0):
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/Library/firehose.py", line 851, in configure
    if "MemoryName" in rsp.data:
TypeError: a bytes-like object is required, not 'str'
wannaphong@wannaphong-dell-g3-3500:~$ edl memorydump
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: ERROR: Failed to authenticate Digital Signature

```

**Comment by bkerler** [comment]
Ah ... VIP protected, so bad luck for you, edl won't be usable. Thanks for reporting however, will add this cpu.

**Comment by wannaphong** [comment]
The cpu is Qualcomm Snapdragon Wear 3100.

**Comment by NickTheOnlyNeko** [comment]
any updates? i tried installing Asteroid OS and then i disabled fastboot and it bricked it's self
if you have figured it out please help me
