### ISSUE TITLE
Error running SierraKeygen on LiveDVD v3

### ISSUE THREAD

**Issue by defrag4** [bkerler/edl#266]
Thank you for the great programming, Using the latest LiveDVD I am able to communicate with my MR1100 via edl without issue

However, I am having problem running sierrakeygen, I believe it is looking for the older version of EDL? I believe the latest version is EDL 3.6 and sierrakeygen is looking for 3.53

Is it possible to revert to 3.53 or resolve error with sierrakeygen so that it will run with 3.6?

user@livedvd:/opt/edl$ sierrakeygen -1 6C510E323D86F237 -d MDM9x50_V1
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.39ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (edlclient 3.60 (/usr/local/lib/python3.9/dist-packages/edlclient-3.60-py3.9.egg), Requirement.parse('edlclient==3.53'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sierrakeygen", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.53', 'sierrakeygen')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'edlclient==3.53' distribution was not found and is required by the application

**Comment by defrag4** [comment]
update: i am an idiot, adding .py to the sierrakeygen line fixed the issue

sierrakeygen.py

**Comment by bkerler** [comment]
Lol ok, considering this is ok, closing the issue now.
