### ISSUE TITLE
im getting this eeeor

### ISSUE THREAD

**Issue by Dylanmurzello** [bkerler/edl#28]
configure,program,firmwarewrite,patch,setbootablestoragedrive,ufs,emmc,power,benchmark,read,getstorageinfo,getcrc16digest,getsha256digest,erase,peek,poke,nop,xml
Traceback (most recent call last):
  File "edl.py", line 1581, in <module>
    main()
  File "edl.py", line 197, in main
    handle_firehose(args, cdc, sahara, verbose)
  File "edl.py", line 989, in handle_firehose
    int(arguments["--gpt-part-entry-start-lba"]))
  File "E:\nokia 8110\zzzznokia\edl-master\Library\firehose.py", line 542, in get_gpt
    data = self.cmd_read_buffer(lun, 0, 2, False)
  File "E:\nokia 8110\zzzznokia\edl-master\Library\firehose.py", line 499, in cmd_read_buffer
    if "value" in rsp[1]:
TypeError: a bytes-like object is required, not 'str'

**Comment by bkerler** [comment]
This means that the phone did not send a response. I've fixed it in the latest commit e93ea64.
