### ISSUE TITLE
Xiaomi redmi note 4 (mido);  TypeError: 'response' object is not subscriptable

### ISSUE THREAD

**Issue by qwerty-in-me** [bkerler/edl#281]
using the toolkit as per README instructions I installed it and attempted to use it by invoking

`edl rl .` the dot directory references `/home/user/edl` for practical purposes

the output of witch is
```

Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
[...]
main - Device detected :)
sahara - Protocol version: 2.1
main - Mode detected: sahara
sahara -`
------------------------
HWID:              0x000460e100000000 (MSM_ID:0x000460e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "MSM8953"

PK_HASH:           0x57158eaf1814d78fd2b3105ece4db18a817a08ac664a5782a925f3ff8403d39a
Serial:            0x01e8bd22

sahara - Detected loader: /usr/lib/python3.10/site-packages/edlclient/../Loaders/xiaomi/EDLAuth/000460e100000000_57158eaf1814d78f_fhprg_edlauth_peek.bin
sahara - Protocol version: 2.1
sahara - Uploading loader /usr/lib/python3.10/site-packages/edlclient/../Loaders/xiaomi/EDLAuth/000460e100000000_57158eaf1814d78f_fhprg_edlauth_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose - Xiaomi EDL Auth detected.
Traceback (most recent call last):
  File "/usr/bin/edl", line 380, in <module>
    base.run()
  File "/usr/bin/edl", line 375, in run
    if fh.connect(sahara):
  File "/usr/lib/python3.10/site-packages/edlclient/Library/firehose_client.py", line 109, in connect
    if self.firehose.configure(0):
  File "/usr/lib/python3.10/site-packages/edlclient/Library/firehose.py", line 880, in configure
    if self.modules.edlauth():
  File "/usr/lib/python3.10/site-packages/edlclient/Library/Modules/init.py", line 71, in edlauth
    return self.xiaomi.edl_auth()
  File "/usr/lib/python3.10/site-packages/edlclient/Library/Modules/xiaomi.py", line 38, in edl_auth
    if rsp[0]:
TypeError: 'response' object is not subscriptable
```

I'd add the debug log file, but I can't upload it with my spotty inet connection

using a different loader (prog_emmc_firehose_8953_ddr_gen.mbn) hangs indefinately
reason I tried a different loader is because [alephsecurity.com](https://alephsecurity.com/2018/01/22/qualcomm-edl-1/) had compiled a list of loaders and prog_emmc_firehose_8953_ddr_gen.mbn was tested to work with a Redmi Note 4x (mido)

I'd fix it myself and issue a patch, but I have no experience with python

**Comment by qwerty-in-me** [comment]
after trying a different loader speciffically prog_emmc_firehose_8953_ddr_xiaomi.mbn I was able to dump the rom.

anyone else encountering such issues should search for any chipset compatible loaders( generic or otherwise ) 

perhaps a better loader detection mechanism might be in order, but what do I know?
