### ISSUE TITLE
USBError(5, 'Input/Output Error')

### ISSUE THREAD

**Issue by spankyMcBonerson** [bkerler/edl#282]
```
firehose - Peek: Address(0x100000),Size(0x1ffb0)
Progress: |██████████████████████████████████████------------|  75.0% Complete                                                                                                                                        DeviceClass - USBError(5, 'Input/Output Error')
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/edlclient-3.60-py3.7.egg/EGG-INFO/scripts/edl", line 380, in <module>
    base.run()
  File "/usr/local/lib/python3.7/dist-packages/edlclient-3.60-py3.7.egg/EGG-INFO/scripts/edl", line 376, in run
    fh.handle_firehose(cmd, options)
  File "/usr/local/lib/python3.7/dist-packages/edlclient-3.60-py3.7.egg/edlclient/Library/firehose_client.py", line 389, in handle_firehose
    if self.firehose.cmd_peek(target_name[0][0], target_name[0][1], filename, True):
  File "/usr/local/lib/python3.7/dist-packages/edlclient-3.60-py3.7.egg/edlclient/Library/firehose.py", line 1440, in cmd_peek
    rdata = self.xml.getlog(tmp)[0].replace("0x", "").replace(" ", "")
IndexError: list index out of range
```

don't know if it matters but i'm running :
 python3 version: 3.7.5-1

and here is the full output:
[error.txt](https://github.com/bkerler/edl/files/8666831/error.txt)

**Comment by bkerler** [comment]
Looks like an usb timeout has happened. I recommend to change the usb port / usb hub / cable.
