### ISSUE TITLE
ModuleNotFoundError: No module named 'docopt'

### ISSUE THREAD

**Issue by Leminh8686** [bkerler/edl#29]
how to fix pls help me

C:\Users\Admin\Desktop\edl-master\edl-master>@python\python.exe edl.py rl dumps --memory=ufs --genxml
Traceback (most recent call last):
  File "edl.py", line 105, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

**Comment by firefresh** [comment]
Check, is usual error in the python path: 
https://stackoverflow.com/questions/42512817/fatal-python-error-on-windows-10-modulenotfounderror-no-module-named-encodings

**Comment by Leminh8686** [comment]
> Check, is usual error in the python path:
> https://stackoverflow.com/questions/42512817/fatal-python-error-on-windows-10-modulenotfounderror-no-module-named-encodings

tks sir but iam bug 
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Admin\Desktop\edl-master\EDL 2.1\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-_3qi0w72\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-_3qi0w72\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-vg4cbgia'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-_3qi0w72\pycryptodome\
    Complete output (20 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-_3qi0w72\pycryptodome\setup.py", line 457, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-_3qi0w72\pycryptodome\compiler_opt.py", line 341, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-_3qi0w72\pycryptodome\compiler_opt.py", line 251, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-_3qi0w72\pycryptodome\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "C:\Program Files\Python310\Lib\distutils\_msvccompiler.py", line 323, in compile
        self.initialize()
      File "C:\Program Files\Python310\Lib\distutils\_msvccompiler.py", line 220, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Program Files\Python310\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Program Files\Python310\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    Testing support for clang
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by bkerler** [comment]
you need to run "pip3 install -r requirements.txt" as stated in the readme.
