### ISSUE TITLE
name 'i' Is not defined

### ISSUE THREAD

**Issue by Rgamer84** [bkerler/edl#298]
I've used this many times before and it appears that something was borked in a recent update.  See below output

username@computer:/edl$ sierrakeygen.py -l BE96CBBEE0829BCA -d MDM9x30
Traceback (most recent call last):
  File "/usr/local/bin/sierrakeygen.py", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'sierrakeygen.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/sierrakeygen.py", line 593, in <module>
    main(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/sierrakeygen.py", line 582, in main
    resp = kg.keygen.run(devicegeneration, openlock, 0)
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/sierrakeygen.py", line 178, in run
    resp = self.SierraKeygen(challenge=challenge, key=key, challengelen=challengelen, keylen=16)[:challengelen]
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/sierrakeygen.py", line 316, in SierraKeygen
    exec(prodtable[self.devicegeneration]["run"]) # uses challenge
  File "<string>", line 1, in <module>
NameError: name 'i' is not defined. Did you mean: 'id'?
username@computer:~/edl$

**Comment by Rgamer84** [comment]
Issue resolved with latest pull
