### ISSUE TITLE
usb.core.USBError: [Errno 5] Input/Output Error

### ISSUE THREAD

**Issue by firefresh** [bkerler/edl#30]
Hello, I am trying to unbrick a cell phone and when I try this command it throws me the following:

OS: Kali Linux 32 bits (I'm thinking this is the problem or the phone memory is dead, idk)
(All the libraries and required python install it correctly)

`
root@bangho-atom:/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master# sudo python3 edl.py wl unbrick --loader=unbrick/prog_emmc_firehose_zte_8909.mbn && sudo python3 edl.py reset >> error.txt
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2020.
__main__ - Using loader unbrick/prog_emmc_firehose_zte_8909.mbn ...
__main__ - Waiting for the device
__main__ - Device detected :)
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5
Traceback (most recent call last):
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 322, in connect
    v = self.cdc.read()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 259, in read
    raise(e)
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 243, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "/usr/local/lib/python3.8/dist-packages/usb/core.py", line 1017, in read
    ret = fn(
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 846, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 338, in connect
    res = self.cdc.read()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 259, in read
    raise(e)
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 243, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "/usr/local/lib/python3.8/dist-packages/usb/core.py", line 1017, in read
    ret = fn(
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 846, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "edl.py", line 223, in doconnect
    mode, resp = sahara.connect()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 345, in connect
    res = self.cdc.read()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 259, in read
    raise(e)
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 243, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "/usr/local/lib/python3.8/dist-packages/usb/core.py", line 1017, in read
    ret = fn(
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 846, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 322, in connect
    v = self.cdc.read()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 259, in read
    raise(e)
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 243, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "/usr/local/lib/python3.8/dist-packages/usb/core.py", line 1017, in read
    ret = fn(
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 846, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 338, in connect
    res = self.cdc.read()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 259, in read
    raise(e)
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 243, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "/usr/local/lib/python3.8/dist-packages/usb/core.py", line 1017, in read
    ret = fn(
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 846, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "edl.py", line 1589, in <module>
    main()
  File "edl.py", line 162, in main
    mode, resp = doconnect(cdc, loop, mode, resp, sahara)
  File "edl.py", line 228, in doconnect
    mode, resp = sahara.connect()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 345, in connect
    res = self.cdc.read()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 259, in read
    raise(e)
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/usblib.py", line 243, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "/usr/local/lib/python3.8/dist-packages/usb/core.py", line 1017, in read
    ret = fn(
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 846, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error
`

**Comment by firefresh** [comment]
I try another thing and:

`
root@bangho-atom:/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master# python3 edl.py wl unbrick --loader=unbrick/prog_emmc_firehose_zte_8909.mbn && python3 edl.py reset
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2020.
__main__ - Using loader unbrick/prog_emmc_firehose_zte_8909.mbn ...
__main__ - Waiting for the device
__main__ - Device detected :)
__main__ - Mode detected: sahara
Device is in EDL mode .. continuing.
Library.sahara - 
------------------------
HWID:              0x007050e100040000 (MSM_ID:0x007050e1,OEM_ID:0x0004,MODEL_ID:0x0000)
PK_HASH:           0xf02215c75cf9f072c149ab18f373cef5567c9ae1e3a4ed521c232e676bac8f59
Serial:            0x0d0c1b5b
SBL Version:       0x00000000

Library.sahara - Unexpected error on uploading, maybe signature of loader wasn't accepted ?
Successfully uploaded programmer :)
__main__ - Sorry, couldn't talk to Sahara, please reboot the device !
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2020.
__main__ - Trying with no loader given ...
__main__ - Waiting for the device
__main__ - Device detected :)
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5
Traceback (most recent call last):
  File "edl.py", line 223, in doconnect
    mode, resp = sahara.connect()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 351, in connect
    cmd, pkt = self.get_rsp()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 279, in get_rsp
    pkt = read_object(v[0:0x2*0x4], self.pkt_cmd_hdr)
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/utils.py", line 269, in read_object
    obj[name] = struct.unpack(stype, data[pos:pos+struct.calcsize(stype)])[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "edl.py", line 1589, in <module>
    main()
  File "edl.py", line 162, in main
    mode, resp = doconnect(cdc, loop, mode, resp, sahara)
  File "edl.py", line 228, in doconnect
    mode, resp = sahara.connect()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 351, in connect
    cmd, pkt = self.get_rsp()
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/sahara.py", line 279, in get_rsp
    pkt = read_object(v[0:0x2*0x4], self.pkt_cmd_hdr)
  File "/media/bangho/DATOS/PROYECTOS/unbrick_something/edl-master/Library/utils.py", line 269, in read_object
    obj[name] = struct.unpack(stype, data[pos:pos+struct.calcsize(stype)])[0]
struct.error: unpack requires a buffer of 4 bytes

`

**Comment by firefresh** [comment]
Ok i try in Linux Mint 20 64 bits and the same:

```
root@optimus-ryzen:/home/optimus/unbrick_something/edl-master# ./edl.py wl unbrick --loader=unbrick/prog_emmc_firehose_8953_ddr.mbn && ./edl.py reset
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2020.
__main__ - Using loader unbrick/prog_emmc_firehose_8953_ddr.mbn ...
__main__ - Waiting for the device
__main__ - Device detected :)
__main__ - Mode detected: sahara
Device is in EDL mode .. continuing.
Library.sahara - 
------------------------
HWID:              0x007050e100040000 (MSM_ID:0x007050e1,OEM_ID:0x0004,MODEL_ID:0x0000)
PK_HASH:           0xf02215c75cf9f072c149ab18f373cef5567c9ae1e3a4ed521c232e676bac8f59
Serial:            0x0d0c1b5b
SBL Version:       0x00000000

Library.sahara - Unexpected error on uploading, maybe signature of loader wasn't accepted ?
Successfully uploaded programmer :)
__main__ - Sorry, couldn't talk to Sahara, please reboot the device !
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2020.
__main__ - Trying with no loader given ...
__main__ - Waiting for the device
__main__ - Device detected :)
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5
Traceback (most recent call last):
  File "./edl.py", line 223, in doconnect
    mode, resp = sahara.connect()
  File "/home/optimus/unbrick_something/edl-master/Library/sahara.py", line 351, in connect
    cmd, pkt = self.get_rsp()
  File "/home/optimus/unbrick_something/edl-master/Library/sahara.py", line 279, in get_rsp
    pkt = read_object(v[0:0x2*0x4], self.pkt_cmd_hdr)
  File "/home/optimus/unbrick_something/edl-master/Library/utils.py", line 269, in read_object
    obj[name] = struct.unpack(stype, data[pos:pos+struct.calcsize(stype)])[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./edl.py", line 1589, in <module>
    main()
  File "./edl.py", line 162, in main
    mode, resp = doconnect(cdc, loop, mode, resp, sahara)
  File "./edl.py", line 228, in doconnect
    mode, resp = sahara.connect()
  File "/home/optimus/unbrick_something/edl-master/Library/sahara.py", line 351, in connect
    cmd, pkt = self.get_rsp()
  File "/home/optimus/unbrick_something/edl-master/Library/sahara.py", line 279, in get_rsp
    pkt = read_object(v[0:0x2*0x4], self.pkt_cmd_hdr)
  File "/home/optimus/unbrick_something/edl-master/Library/utils.py", line 269, in read_object
    obj[name] = struct.unpack(stype, data[pos:pos+struct.calcsize(stype)])[0]
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by bkerler** [comment]
It looks like you are trying to use a loader which has a pkhash different to the device you have.
