### ISSUE TITLE
'NoneType' object has no attribute 'totalsectors'

### ISSUE THREAD

**Issue by mfn003** [bkerler/edl#313]
Device is Lenovo A2020a40.
```
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x009600e100000000 (MSM_ID:0x009600e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "MSM8909"
PK_HASH:           0xcc3153a80293939b90d02d3bf8b23e0292e452fef662c74998421adad42a380f
Serial:            0x06eb78f7

sahara - Possibly unfused device detected, so any loader should be fine...
sahara - Trying loader: /usr/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/qualcomm/model_generic/msm8909/009600e100000000_cc3153a80293939b_fhprg_peek.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /usr/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/qualcomm/model_generic/msm8909/009600e100000000_cc3153a80293939b_fhprg_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose - TargetName=MSM8909
firehose - MemoryName=eMMC
firehose - Version=1
firehose - Trying to read first storage sector...
firehose - Running configure...
firehose_client - Supported functions:
-----------------
firehose_client - [qfil] raw programming...
firehose_client - [qfil] programming gptraw.xml
firehose
firehose - [LIB]: 'NoneType' object has no attribute 'totalsectors'
firehose_client - [qfil] programming ./gpt_main0.bin to partition(0)@sector(0)...
firehose - 
Writing to physical partition 0, sector 0, sectors 34
Done |--------------------------------------------------|   0.0% Write (Sector 0Progress: |██████████████████████████████████████████████████| 100.0% Write (Sector 0x22 of 0x22, ) 1.86 MB/s
firehose
firehose - [LIB]: Error:{}
firehose
firehose - [LIB]: Write failed Sector 0, Errno 3
firehose
firehose - [LIB]: Finished sector address 0
firehose
firehose - [LIB]: 'NoneType' object has no attribute 'totalsectors'
firehose_client - [qfil] programming ./gpt_backup0.bin to partition(0)@sector(-34)...
firehose - 
Writing to physical partition 0, sector -34, sectors 33
Done |--------------------------------------------------|   0.0% Write (Sector 0x0 of 0x21) 0.00 MB/s                               Traceback (most recent call last):
  File "/usr/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 391, in <module>
    base.run()
  File "/usr/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 386, in run
    fh.handle_firehose(cmd, options)
  File "/usr/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/firehose_client.py", line 908, in handle_firehose
    for evt, elem in ET.iterparse(fl, events=["end"]):
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1260, in iterator
    root = pullparser._close_and_return_root()
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1307, in _close_and_return_root
    root = self._parser.close()
xml.etree.ElementTree.ParseError: no element found: line 8, column 0
```

**Comment by bkerler** [comment]
Can you upload the xml ?

**Comment by mfn003** [comment]
I think the eMMC is straight up fried, do you still want it?
