### ISSUE TITLE
Realme GT Master Edition - Stuck on "Mode Detected - sahara"

### ISSUE THREAD

**Issue by GarnetSunset** [bkerler/edl#319]
```# edl --serial
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main
main - [LIB]: Please first install libusb_win32 driver from Zadig
main - Trying with no loader given ...
main - Waiting for the device
Detected 0x5c6:0x9008 device at: COM8
main - Device detected :)
DeviceClass - Warning !
main - Mode detected: sahara
```

Any tips on why this might be happening? Left it for about 5 mins and no luck, and with commands same issue.

Edit: this happens on both linux and windows

debugmode output 

```james@pop-os:/media/james/FUCK/RMX3363export_11_A.04_2021080317040000/rmx3363$ edl --serial qfil rawprogram0.xml patch0.xml . --debugmode
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'mprg8974'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'mprg8626'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'mprg8974'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
main - Trying with no loader given ...
main - Waiting for the device
Detected 0x5c6:0x9008 device at: /dev/ttyUSB0
main - Device detected :)
DeviceClass - Warning !
DeviceClass
DeviceClass - [LIB]: read:0x0
DeviceClass
DeviceClass - [LIB]: ['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 391, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 299, in run\n    conninfo = self.doconnect(loop)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 213, in doconnect\n    resp = self.sahara.connect()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/sahara.py", line 111, in connect\n    v = self.cdc.read(length=0xC * 0x4,timeout=1)\n']
DeviceClass
DeviceClass - [LIB]: RX:
DeviceClass
DeviceClass - [LIB]: ['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 391, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 299, in run\n    conninfo = self.doconnect(loop)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 213, in doconnect\n    resp = self.sahara.connect()\n']
DeviceClass
DeviceClass - [LIB]: TX:<?xml version="1.0" ?><data><nop /></data>
DeviceClass
DeviceClass - [LIB]: read:0x10
DeviceClass
DeviceClass - [LIB]: ['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 391, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 299, in run\n    conninfo = self.doconnect(loop)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 213, in doconnect\n    resp = self.sahara.connect()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/sahara.py", line 131, in connect\n    res = self.cdc.read(timeout=1)\n']
DeviceClass
DeviceClass - [LIB]: RX:04000000100000000d00000001000000
main - Mode detected: sahara
DeviceClass
DeviceClass - [LIB]: ['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 391, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 374, in run\n    sc.handle_streaming(cmd, options)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/streaming_client.py", line 79, in handle_streaming\n    if self.streaming.connect(mode):\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/streaming.py", line 779, in connect\n    resp = self.send(cmdbuf, True)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/streaming.py", line 996, in send\n    return self.hdlc.send_cmd_np(cmd, nocrc)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/hdlc.py", line 229, in send_cmd_np\n    return self.send_cmd_base(outdata, 0, nocrc)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/hdlc.py", line 218, in send_cmd_base\n    if self.send_unframed_buf(packet, prefixflag):\n']
DeviceClass
DeviceClass - [LIB]: TX:11001200a0e30000c1e50140a0e31eff2fe14bd97e


```

Update: After leaving it for like 20 mins, got this!

```DeviceClass
DeviceClass - [LIB]: TX:11001200a0e30000c1e50140a0e31eff2fe14bd97e
DeviceClass
DeviceClass - [LIB]: read:0x10
DeviceClass
DeviceClass - [LIB]: ['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 391, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 374, in run\n    sc.handle_streaming(cmd, options)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/streaming_client.py", line 79, in handle_streaming\n    if self.streaming.connect(mode):\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/streaming.py", line 779, in connect\n    resp = self.send(cmdbuf, True)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/streaming.py", line 996, in send\n    return self.hdlc.send_cmd_np(cmd, nocrc)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/hdlc.py", line 229, in send_cmd_np\n    return self.send_cmd_base(outdata, 0, nocrc)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/hdlc.py", line 220, in send_cmd_base\n    return self.receive_reply_nocrc()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/hdlc.py", line 174, in receive_reply_nocrc\n    tmp = self.cdc.read(timeout=timeout)\n']
DeviceClass
DeviceClass - [LIB]: RX:04000000100000000d00000001000000
streaming_client
streaming_client - [LIB]: Unknown/Missing command, a command is required.
```

Another edit: When trying to write one boot img it takes a long time and crashes too. 

```# edl w boot .\boot.img --serial
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main
main - [LIB]: Please first install libusb_win32 driver from Zadig
main - Trying with no loader given ...
main - Waiting for the device
Detected 0x5c6:0x9008 device at: COM8
main - Device detected :)
DeviceClass - Warning !
main - Mode detected: sahara
Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python39\Scripts\edl.py", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "C:\Users\James\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\James\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "c:\users\james\appdata\local\programs\python\python39\lib\site-packages\edlclient-3.60-py3.9.egg\EGG-INFO\scripts\edl", line 391, in <module>
    base.run()
  File "c:\users\james\appdata\local\programs\python\python39\lib\site-packages\edlclient-3.60-py3.9.egg\EGG-INFO\scripts\edl", line 374, in run
    sc.handle_streaming(cmd, options)
  File "C:\Users\James\AppData\Local\Programs\Python\Python39\lib\site-packages\edlclient-3.60-py3.9.egg\edlclient\Library\streaming_client.py", line 354, in handle_streaming
    rpartitions = self.streaming.get_partitions(partitionfilename)
  File "C:\Users\James\AppData\Local\Programs\Python\Python39\lib\site-packages\edlclient-3.60-py3.9.egg\edlclient\Library\streaming.py", line 650, in get_partitions
    with open(filename, "rb") as rf:
TypeError: expected str, bytes or os.PathLike object, not NoneType```

**Comment by GarnetSunset** [comment]
Updated with two more examples

**Comment by AgafDL** [comment]
A similar situation, as in the first message.

**Comment by skoll43** [comment]
same with the 

> loader_utils - [LIB]: 'str' object has no attribute 'append'
> loader_utils
> loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
> loader_utils
> loader_utils - [LIB]: 'str' object has no attribute 'append'
> loader_utils
> loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
> loader_utils

**Comment by amanf244** [comment]
Did you find solution?

**Comment by Xryphon** [comment]
I have the same issue, not sure how this is supposed to be solved as only the serial mode works as of now.

**Comment by 44yu5h** [comment]
As stated by @bkerler 

> If you use windows, only serial will work. With usb on windows, the initial request will fail for an unknown reason

As of now this is the situation. You might want to use Linux for the time being. This issue can be closed I think

**Comment by Ferxkw** [comment]
in windows The solution that I can offer you is to install [QHSUSB_BULK] and libusb. greetings
