### ISSUE TITLE
ERROR: 'response' object is not subscriptable on onclite (Redmi 7)

### ISSUE THREAD

**Issue by aryankaran** [bkerler/edl#339]
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader prog_emmc_firehose_8953_ddr.mbn ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x000ba0e100720000 (MSM_ID:0x000ba0e1,OEM_ID:0x0072,MODEL_ID:0x0000)
CPU detected:      "SDM632"
PK_HASH:           0x57158eaf1814d78fd2b3105ece4db18a817a08ac664a5782a925f3ff8403d39a
Serial:            0x06b2fd42

sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader prog_emmc_firehose_8953_ddr.mbn ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose - Xiaomi EDL Auth detected.
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 391, in <module>
    base.run()
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 385, in run
    if fh.connect(sahara):
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/firehose_client.py", line 109, in connect
    if self.firehose.configure(0):
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/firehose.py", line 887, in configure
    if self.modules.edlauth():
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/Modules/init.py", line 71, in edlauth
    return self.xiaomi.edl_auth()
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/Modules/xiaomi.py", line 38, in edl_auth
    if rsp[0]:
TypeError: 'response' object is not subscriptable

i tried using existing loader as well as the factory one but still same typerrror .. x[

**Comment by 44yu5h** [comment]
I don't know if you still need it but [here](https://androidfilehost.com/?fid=10763459528675599938). Try this.
Or [this](https://drive.google.com/file/d/1ZdoEu4m9gFcgKCXqFUIMPWYQ5VUV0sym/view) (no auth loader)

**Comment by bkerler** [comment]
Adding the loader with commit 
1f014d6
