### ISSUE TITLE
NotImplementedError: Operation not supported or unimplemented on this platform

### ISSUE THREAD

**Issue by KyleSanderson** [bkerler/edl#349]
$ ./edl reset
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
Traceback (most recent call last):
  File "C:\Users\Llamar\Downloads\edl\edl", line 391, in <module>
    base.run()
  File "C:\Users\Llamar\Downloads\edl\edl", line 299, in run
    conninfo = self.doconnect(loop)
  File "C:\Users\Llamar\Downloads\edl\edl", line 193, in doconnect
    self.cdc.connected = self.cdc.connect(portname=self.portname)
  File "C:\Users\Llamar\Downloads\edl\edlclient\Library\Connection\usblib.py", line 226, in connect
    self.configuration = self.device.get_active_configuration()
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 921, in get_active_configuration
    return self._ctx.get_active_configuration(self)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 249, in get_active_configuration
    self.managed_open()
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\backend\libusb1.py", line 600, in _check
    raise NotImplementedError(_strerror(ret))
NotImplementedError: Operation not supported or unimplemented on this platform

**Comment by lentas1** [comment]
same

**Comment by lentas1** [comment]
fucking edl

**Comment by bkerler** [comment]
Windows issue, sorry :(

**Comment by chelming** [comment]
for what it's worth, I was able to get past this by installing [Zadig](https://zadig.akeo.ie/) and changing the driver over to the WinUSB driver. 

![image](https://github.com/bkerler/edl/assets/7746625/2c3a6e88-56e0-42b4-b43e-b2be2744e377)

**Comment by theXappy** [comment]
Hey, @chelming 's solution also worked for me but I had to enable "List All Devices" after entering edl mode and before "QUSB_BULK" was available in the drop down:
![{2DB56BAE-9A30-4DD2-8A07-7C3F6F18A09E}](https://github.com/user-attachments/assets/af29ee2a-b4f7-44b9-8404-946799b0a4a4)
