### ISSUE TITLE
Timeout with Streaming mode

### ISSUE THREAD

**Issue by sgulls** [bkerler/edl#38]
Streaming mode is now supported with commit 036bc63

_Originally posted by @bkerler in https://github.com/bkerler/edl/issues/33#issuecomment-749784139_

Still have issues with it sending commands 

```
default@deb:~/edl$ python3 ./edl.py printgpt --loader=Loaders/0000000000000000_b53fb23d1953decb_FHPRG.bin --vid 0846 --pid 68e0 --debugmode
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client V3 (c) B.Kerler 2018-2020.
Library.utils - Using loader Loaders/0000000000000000_b53fb23d1953decb_FHPRG.bin ...
Library.utils - Waiting for the device
Library.utils - Ohuh
Library.utils -   CONFIGURATION 1: 2 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x2c (44 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0
   bmAttributes         :   0xa0 Bus Powered, Remote Wakeup
   bMaxPower            :    0x1 (2 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x0
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x400 (1024 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x400 (1024 bytes)
       bInterval        :    0x0
Library.utils - Device detected :)
Library.utils - connect:0x80
Library.utils - Timed out
Library.utils - b''
Library.utils - TX:7e11001200a0e30000c1e50140a0e31eff2fe14bd97e
Library.utils - connect:0x80
Library.utils - RX:7e0d1600000000884d7e
Library.utils - TX:0c0000000c00000003000000
Library.utils - TX:<?xml version="1.0" ?><data><nop /></data>
Library.utils - connect:0x80
Library.utils - Timed out
Library.utils - b''
Library.utils - TX:0c0000000c00000002000000
Library.utils - get_rsp:0x80
Library.utils - Timed out
Library.utils - b''
Library.utils - connect:0x80
Library.utils - Timed out
Library.utils - b''
Library.utils - TX:7e11001200a0e30000c1e50140a0e31eff2fe14bd97e
Library.utils - connect:0x80
Library.utils - RX:7e0d1600000000884d7e
Library.utils - TX:0c0000000c00000003000000
Library.utils - TX:<?xml version="1.0" ?><data><nop /></data>
Library.utils - connect:0x80
Library.utils - Timed out
Library.utils - b''
Library.utils - TX:0c0000000c00000002000000
Library.utils - get_rsp:0x80
Library.utils - Timed out
Library.utils - b''
Traceback (most recent call last):
  File "./edl.py", line 140, in doconnect
    mode, resp = sahara.connect()
  File "/home/default/edl/Library/sahara.py", line 379, in connect
    cmd, pkt = self.get_rsp()
  File "/home/default/edl/Library/sahara.py", line 294, in get_rsp
    pkt = read_object(v[0:0x2 * 0x4], self.pkt_cmd_hdr)
  File "/home/default/edl/Library/utils.py", line 464, in read_object
    obj[name] = struct.unpack(stype, data[pos:pos + struct.calcsize(stype)])[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./edl.py", line 363, in <module>
    main()
  File "./edl.py", line 268, in main
    mode, resp = doconnect(cdc, loop, mode, resp, sahara)
  File "./edl.py", line 145, in doconnect
    mode, resp = sahara.connect()
  File "/home/default/edl/Library/sahara.py", line 379, in connect
    cmd, pkt = self.get_rsp()
  File "/home/default/edl/Library/sahara.py", line 294, in get_rsp
    pkt = read_object(v[0:0x2 * 0x4], self.pkt_cmd_hdr)
  File "/home/default/edl/Library/utils.py", line 464, in read_object
    obj[name] = struct.unpack(stype, data[pos:pos + struct.calcsize(stype)])[0]
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by sgulls** [comment]
Which Linux Distro are you using? I'm on Debian 10/Buster

**Comment by sgulls** [comment]
After a certain period of time, the MR1100 will stop flashing its LED from the orange/blue it does when entering EDL to just straight orange. When I try to send the command, here's the debug log. It will also automatically reset the device:

```
 default  deb  ☎  ~  edl   master  1✎  2+  ERROR  %    python3 ./edl.py printgpt --loader=Loaders/0000000000000000_b53fb23d1953decb_FHPRG.bin --vid=0x0846 --pid=0x68e0 --debugmode
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client V3 (c) B.Kerler 2018-2020.
Library.utils - Using loader Loaders/0000000000000000_b53fb23d1953decb_FHPRG.bin ...
Library.utils - Waiting for the device
Library.utils - Ohuh
Library.utils -   CONFIGURATION 1: 2 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x2c (44 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0
   bmAttributes         :   0xa0 Bus Powered, Remote Wakeup
   bMaxPower            :    0x1 (2 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x0
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x400 (1024 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x400 (1024 bytes)
       bInterval        :    0x0
Library.utils - Device detected :)
Library.utils - connect:0x80
Library.utils - RX:7e0d190000000074277e
Library.utils - get_rsp:0x80
USBError(19, 'No such device (it may have been disconnected)') <class 'usb.core.USBError'> 19
Library.utils - Couldn't detect the device. Is it connected ?
Library.utils - connect:0x80
Library.sahara - 'NoneType' object has no attribute 'read'
Library.utils - connect:0x80
Library.sahara - 'NoneType' object has no attribute 'read'
Library.utils - Unknown mode. Aborting.
```

**Comment by bkerler** [comment]
I haven't tested mr1100 (no support for mdm9x55 yet). But you need to use a patched loader for streaming, otherwise the cmd 11 will just reboot the device.

**Comment by bkerler** [comment]
Just tested a mr1100. I had to fix a few things, like bcr causing issues. However, you will need the device to be in pid 9008 mode. Any other mode like 900e won't work as the mpu will prevent accessing nand.
