### ISSUE TITLE
TypeError: 'response' object is not subscriptable

### ISSUE THREAD

**Issue by 44yu5h** [bkerler/edl#389]
What is it that I'm doing wrong?

This was edl 3.1's response but the latest one also spits out the same thing. Thanks!!

```
feitlimit@pop-os:~/Desktop/edl$ edl printgpt --memory=UFS
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara -
------------------------
HWID: 0x000460e100000000 (MSM_ID:0x000460e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected: "MSM8953"
PK_HASH: 0x57158eaf1814d78fd2b3105ece4db18a817a08ac664a5782a925f3ff8403d39a
Serial: 0xb94b1788

sahara - Detected loader: /usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/xiaomi/EDLAuth/000460e100000000_57158eaf1814d78f_fhprg_edlauth_peek.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/xiaomi/EDLAuth/000460e100000000_57158eaf1814d78f_fhprg_edlauth_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose - Xiaomi EDL Auth detected.
Traceback (most recent call last):
File "/usr/local/bin/edl", line 4, in <module>
__import__('pkg_resources').run_script('edlclient==3.60', 'edl')
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
exec(code, namespace, namespace)
File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 393, in <module>
base.run()
File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/EGG-INFO/scripts/edl", line 387, in run
if fh.connect(sahara):
File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/firehose_client.py", line 109, in connect
if self.firehose.configure(0):
File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/firehose.py", line 907, in configure
if self.modules.edlauth():
File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/Modules/init.py", line 71, in edlauth
return self.xiaomi.edl_auth()
File "/usr/local/lib/python3.10/dist-packages/edlclient-3.60-py3.10.egg/edlclient/Library/Modules/xiaomi.py", line 38, in edl_auth
if rsp[0]:
TypeError: 'response' object is not subscriptable
```

**Comment by 44yu5h** [comment]
#281, I removed the existing loader and installed the one in the link. It worked. 
But now despite showing reset successful on ```edl reset``` it doesn't seem to exit edl mode. Maybe I'll figure that out someday.
