### ISSUE TITLE
TypeError: 'response' object is not subscriptable (Xiaomi)

### ISSUE THREAD

**Issue by mrcrdwd** [bkerler/edl#393]
Trying to revive a dead Xiaomi Mi Pad 4. There seems to be some life in it but I can't manage to flash it. Any clues are much appreciated!

Attaching [log.txt](https://github.com/bkerler/edl/files/11304541/log.txt) with debug info.

```sh
Capstone library is missing (optional).
Keystone library is missing (optional).
No module named 'Cryptodome'
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara -
------------------------
HWID:              0x0009c0e100000000 (MSM_ID:0x0009c0e1,OEM_ID:0x0000,MODEL_ID:0x0000)
Unknown CPU, please send log as issue to https://github.com/bkerler/edl
PK_HASH:           0xa7b8b82545a98eca23d6e9105fb464568d1b5828264903441bdef0cd57e3c370
Serial:            0x1bcc732e

sahara - Found possible loader: /opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/../Loaders/xiaomi/0008c0e100010000_a7b8b82545a98eca_fhprg_peek.bin
sahara - Found possible loader: /opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/../Loaders/xiaomi/0005e0e100010000_a7b8b82545a98eca_fhprg_peek.bin
sahara - Found possible loader: /opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/../Loaders/xiaomi/000930e100010000_a7b8b82545a98eca_fhprg_peek.bin
sahara - Found possible loader: /opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/../Loaders/xiaomi/000930e100720000_a7b8b82545a98eca_fhprg_peek.bin
sahara - Found possible loader: /opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/../Loaders/xiaomi/EDLAuth/0008c0e100720000_a7b8b82545a98eca_fhprg_edlauth.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/../Loaders/xiaomi/EDLAuth/0008c0e100720000_a7b8b82545a98eca_fhprg_edlauth.bin ...
sahara - 64-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose - Binary build date: Dec 26 2018 @ 22:45:00
firehose - Chip serial num: 466383662 (0x1bcc732e)
firehose - Supported Functions: program configure sig nop firmwarewrite patch setbootablestoragedrive ufs emmc power benchmark read getstorageinfo getsha256digest erase
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "UFS" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose - Xiaomi EDL Auth detected.
Traceback (most recent call last):
  File "/opt/homebrew/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/opt/homebrew/lib/python3.11/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/homebrew/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1559, in run_script
    exec(code, namespace, namespace)
  File "/opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/EGG-INFO/scripts/edl", line 393, in <module>
    base.run()
  File "/opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/EGG-INFO/scripts/edl", line 387, in run
    if fh.connect(sahara):
       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/Library/firehose_client.py", line 109, in connect
    if self.firehose.configure(0):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/Library/firehose.py", line 907, in configure
    if self.modules.edlauth():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/Library/Modules/init.py", line 71, in edlauth
    return self.xiaomi.edl_auth()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/edlclient-3.60-py3.11.egg/edlclient/Library/Modules/xiaomi.py", line 38, in edl_auth
    if rsp[0]:
       ~~~^^^
TypeError: 'response' object is not subscriptable
```

**Comment by 44yu5h** [comment]
@bkerler wrong loaders for Xiaomi?

I spent 8 to 12 HOURS on this stupid error. Check #281 
What I did #389
