### ISSUE TITLE
unimplemented on this platform

### ISSUE THREAD

**Issue by suleramaa** [bkerler/edl#406]
Qualcomm Sahara / Firehose Client V3.61 (c) B.Kerler 2018-2023.
main - Trying with no loader given ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold vol dwn + pwr, in fastboot mode connect usb.
        Run "./fastpwn oem edl".
main - Other:  Run "adb reboot edl".

...............
..........Traceback (most recent call last):
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Scripts\edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "c:\users\next_level\appdata\local\programs\python\python311\lib\site-packages\edlclient-3.60-py3.11.egg\EGG-INFO\scripts\edl", line 393, in <module>
    base.run()
  File "c:\users\next_level\appdata\local\programs\python\python311\lib\site-packages\edlclient-3.60-py3.11.egg\EGG-INFO\scripts\edl", line 301, in run
    conninfo = self.doconnect(loop)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\users\next_level\appdata\local\programs\python\python311\lib\site-packages\edlclient-3.60-py3.11.egg\EGG-INFO\scripts\edl", line 193, in doconnect
    self.cdc.connected = self.cdc.connect(portname=self.portname)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\edlclient-3.60-py3.11.egg\edlclient\Library\Connection\usblib.py", line 226, in connect
    self.configuration = self.device.get_active_configuration()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 921, in get_active_configuration
    return self._ctx.get_active_configuration(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 249, in get_active_configuration
    self.managed_open()
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "C:\Users\NEXT_LEVEL\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb1.py", line 600, in _check
    raise NotImplementedError(_strerror(ret))
NotImplementedError: Operation not supported or unimplemented on this platform

**Comment by azimeu** [comment]
Is there no way to solve it on windows? I want to use edl script on windows
