### ISSUE TITLE
cant understand whats happening, any hints?

### ISSUE THREAD

**Issue by 99degree** [bkerler/edl#433]
C:\WINDOWS\system32>cd \d_drive\edl

C:\d_drive\edl>python3 edl printgpt --memory=ufs --debugmode --serial
Qualcomm Sahara / Firehose Client V3.61 (c) B.Kerler 2018-2023.
main
main - [LIB]: [33mPlease first install libusb_win32 driver from Zadig[0m
Traceback (most recent call last):
  File "C:\d_drive\edl\edl", line 399, in <module>
    base.run()
  File "C:\d_drive\edl\edl", line 289, in run
    self.cdc = serial_class(loglevel=self.__logger.level, portconfig=portconfig)
  File "C:\d_drive\edl\edlclient\Library\Connection\seriallib.py", line 38, in __init__
    super().__init__(loglevel, portconfig, devclass)
  File "C:\d_drive\edl\edlclient\Library\Connection\devicehandler.py", line 44, in __init__
    fh = logging.FileHandler(logfilename, encoding='utf-8')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\d_drive\\edl\\logs\\log.txt'

C:\d_drive\edl>mkdir logs

C:\d_drive\edl>python3 edl printgpt --memory=ufs --debugmode --serial
Qualcomm Sahara / Firehose Client V3.61 (c) B.Kerler 2018-2023.
main
main - [LIB]: [33mPlease first install libusb_win32 driver from Zadig[0m
main - Trying with no loader given ...
main - Waiting for the device
Detected 0x5c6:0x9008 device at: COM3
main - Device detected :)
DeviceClass - Warning !
DeviceClass
DeviceClass - [LIB]: [95mread:0x0[0m
DeviceClass
DeviceClass - [LIB]: [95m['  File "C:\\d_drive\\edl\\edl", line 399, in <module>\n    base.run()\n', '  File "C:\\d_drive\\edl\\edl", line 306, in run\n    conninfo = self.doconnect(loop)\n', '  File "C:\\d_drive\\edl\\edl", line 218, in doconnect\n    resp = self.sahara.connect()\n', '  File "C:\\d_drive\\edl\\edlclient\\Library\\sahara.py", line 115, in connect\n    v = self.cdc.read(length=0xC * 0x4,timeout=1)\n'][0m
DeviceClass
DeviceClass - [LIB]: [95mRX:[0m

**Comment by 99degree** [comment]
in case below are useful:

~/source/edl# ./fhloaderparse Redmi_Note_9_pro_firehorse/ Loaders
Traceback (most recent call last):
  File "/root/source/edl/./fhloaderparse", line 433, in <module>
    main(sys.argv)
  File "/root/source/edl/./fhloaderparse", line 271, in main
    rt = open(os.path.join(outputdir, argv[1] + ".log"), "w")
FileNotFoundError: [Errno 2] No such file or directory: 'Loaders/Redmi_Note_9_pro_firehorse/.log'
root@LAPTOP-VDEV89N4:~/source/edl# ./fhloaderparse Redmi_Note_9_pro_firehorse Loaders
Error on parsing Redmi_Note_9_pro_firehorse/partition.xml
Error on Redmi_Note_9_pro_firehorse/partition.xml
Error on parsing Redmi_Note_9_pro_firehorse/Mediatek qualcomm spd  Driver.url
Error on Redmi_Note_9_pro_firehorse/Mediatek qualcomm spd  Driver.url
Error on parsing Redmi_Note_9_pro_firehorse/Realme Latest file link.url
Error on Redmi_Note_9_pro_firehorse/Realme Latest file link.url
Error on parsing Redmi_Note_9_pro_firehorse/rawprogram0.xml
Error on Redmi_Note_9_pro_firehorse/rawprogram0.xml
Error on parsing Redmi_Note_9_pro_firehorse/Redmi_Note_9_Pro_FRP_softichnic.bin
Error on Redmi_Note_9_pro_firehorse/Redmi_Note_9_Pro_FRP_softichnic.bin
Error on parsing Redmi_Note_9_pro_firehorse/YOUTUBE CHANNEL SUBSCRIBE.url
Error on Redmi_Note_9_pro_firehorse/YOUTUBE CHANNEL SUBSCRIBE.url
Error on parsing Redmi_Note_9_pro_firehorse/patch0.xml
Error on Redmi_Note_9_pro_firehorse/patch0.xml
Error on parsing Redmi_Note_9_pro_firehorse/gpt_backup0.bin
Error on Redmi_Note_9_pro_firehorse/gpt_backup0.bin
Error on parsing Redmi_Note_9_pro_firehorse/Redmi Full Flash file latest.url
Error on Redmi_Note_9_pro_firehorse/Redmi Full Flash file latest.url
Error on parsing Redmi_Note_9_pro_firehorse/gpt_empty0.bin
Error on Redmi_Note_9_pro_firehorse/gpt_empty0.bin
Error on parsing Redmi_Note_9_pro_firehorse/gpt_both0.bin
Error on Redmi_Note_9_pro_firehorse/gpt_both0.bin
Error on parsing Redmi_Note_9_pro_firehorse/All-model-Mi Account Unlock File-link.url
Error on Redmi_Note_9_pro_firehorse/All-model-Mi Account Unlock File-link.url
Error on parsing Redmi_Note_9_pro_firehorse/gpt_main0.bin
Error on Redmi_Note_9_pro_firehorse/gpt_main0.bin
Error on parsing Redmi_Note_9_pro_firehorse/Redmi_Note_9_Pro_Mi_Account_softichnic.img
Error on Redmi_Note_9_pro_firehorse/Redmi_Note_9_Pro_Mi_Account_softichnic.img
OEM:Xiaomi              MODEL:0000      HWID:0000000000720000   SWID:0000000000000003   SWSIZE: PK_HASH:1bebe3863a6781db4b01086063007334de9e5ca14971c7c4f4358ec9d79cda4692ce5e948c6fd409408f4c919fcadfe3    Redmi_Note_9_pro_firehorse/prog_ufs_firehose_sm6250_ddr.elf     658012
Redmi_Note_9_pro_firehorse/prog_ufs_firehose_sm6250_lite.elf is duplicate of Loaders/Duplicate/0000000000720000_1bebe3863a6781db_fhprg.bin. Skipping

**Comment by 99degree** [comment]
another phone


C:\d_drive\edl>python3 edl --serial --debugmode server
Qualcomm Sahara / Firehose Client V3.61 (c) B.Kerler 2018-2023.
main
main - [LIB]: [33mPlease first install libusb_win32 driver from Zadig[0m
main - Trying with no loader given ...
main - Waiting for the device
Detected 0x5c6:0x9008 device at: COM3
main - Device detected :)
DeviceClass - Warning !
DeviceClass
DeviceClass - [LIB]: [95mread:0x0[0m
DeviceClass
DeviceClass - [LIB]: [95m['  File "C:\\d_drive\\edl\\edl", line 399, in <module>\n    base.run()\n', '  File "C:\\d_drive\\edl\\edl", line 306, in run\n    conninfo = self.doconnect(loop)\n', '  File "C:\\d_drive\\edl\\edl", line 218, in doconnect\n    resp = self.sahara.connect()\n', '  File "C:\\d_drive\\edl\\edlclient\\Library\\sahara.py", line 115, in connect\n    v = self.cdc.read(length=0xC * 0x4,timeout=1)\n'][0m
DeviceClass
DeviceClass - [LIB]: [95mRX:[0m
DeviceClass
DeviceClass - [LIB]: [95m['  File "C:\\d_drive\\edl\\edl", line 399, in <module>\n    base.run()\n', '  File "C:\\d_drive\\edl\\edl", line 306, in run\n    conninfo = self.doconnect(loop)\n', '  File "C:\\d_drive\\edl\\edl", line 218, in doconnect\n    resp = self.sahara.connect()\n'][0m
DeviceClass
DeviceClass - [LIB]: [95mTX:<?xml version="1.0" ?><data><nop /></data>[0m
DeviceClass
DeviceClass - [LIB]: [95mread:0x10[0m
DeviceClass
DeviceClass - [LIB]: [95m['  File "C:\\d_drive\\edl\\edl", line 399, in <module>\n    base.run()\n', '  File "C:\\d_drive\\edl\\edl", line 306, in run\n    conninfo = self.doconnect(loop)\n', '  File "C:\\d_drive\\edl\\edl", line 218, in doconnect\n    resp = self.sahara.connect()\n', '  File "C:\\d_drive\\edl\\edlclient\\Library\\sahara.py", line 135, in connect\n    res = self.cdc.read(timeout=1)\n'][0m
DeviceClass
DeviceClass - [LIB]: [95mRX:04000000100000000d00000001000000[0m
main - Mode detected: sahara
DeviceClass
DeviceClass - [LIB]: [95m['  File "C:\\d_drive\\edl\\edl", line 399, in <module>\n    base.run()\n', '  File "C:\\d_drive\\edl\\edl", line 382, in run\n    sc.handle_streaming(cmd, options)\n', '  File "C:\\d_drive\\edl\\edlclient\\Library\\streaming_client.py", line 83, in handle_streaming\n    if self.streaming.connect(mode):\n', '  File "C:\\d_drive\\edl\\edlclient\\Library\\streaming.py", line 783, in connect\n    resp = self.send(cmdbuf, True)\n', '  File "C:\\d_drive\\edl\\edlclient\\Library\\streaming.py", line 1000, in send\n    return self.hdlc.send_cmd_np(cmd, nocrc)\n', '  File "C:\\d_drive\\edl\\edlclient\\Library\\hdlc.py", line 233, in send_cmd_np\n    return self.send_cmd_base(outdata, 0, nocrc)\n', '  File "C:\\d_drive\\edl\\edlclient\\Library\\hdlc.py", line 222, in send_cmd_base\n    if self.send_unframed_buf(packet, prefixflag):\n'][0m
DeviceClass
DeviceClass - [LIB]: [95mTX:11001200a0e30000c1e50140a0e31eff2fe14bd97e[0m
