### ISSUE TITLE
ModuleNotFoundError: No module named 'Library'

### ISSUE THREAD

**Issue by hib1124** [bkerler/edl#453]
when I run fhloaderparse newstuff Loaders it turns to be like this
Traceback (most recent call last):
  File "/usr/local/bin/fhloaderparse", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'fhloaderparse')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/fhloaderparse", line 16, in <module>
    from Library.utils import elf
ModuleNotFoundError: No module named 'Library'
I've tried copy edlclient/Library folder to /usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/ ,vscode can just identify the Library ,but in terminal it stiil raise exception, what should I do?

**Comment by hib1124** [comment]
I‘ve temporarily solved this problem by running ./fhloaderparse and copy library into edl
