### ISSUE TITLE
Attribute Error Encountered While Attempting to Unlock OnePlus

### ISSUE THREAD

**Issue by AntoineMahe** [bkerler/edl#463]
**Issue Description:**
When trying to unlock a OnePlus device, I encountered an attribute error. Here are the details of the command and the error message I received:

**Command Used:**
```bash
edl modules oemunlock enable --loader Loaders/oneplus/0008b0e10051459b_dd7c5f2e53176bee_fhprg_op6t.bin
```

**Error Message:**
```
modules - [LIB]: 'NoneType' object is not callable
Traceback (most recent call last):
  File "./edl", line 386, in <module>
    base.run()
  File "./edl", line 381, in run
    fh.handle_firehose(cmd, options)
  File "/home/nol/Workspace/edl/edlclient/Library/firehose_client.py", line 901, in handle_firehose
    return self.firehose.modules.run(command=mcommand, args=moptions)
  File "/home/nol/Workspace/edl/edlclient/Library/Modules/__init__.py", line 115, in run
    return self.generic.oem_unlock(enable)
  File "/home/nol/Workspace/edl/edlclient/Library/Modules/generic.py", line 30, in oem_unlock
    if rpartition.sectors <= (0x8000 // self.cfg.SECTOR_SIZE_IN_BYTES):
AttributeError: 'generic' object has no attribute 'cfg'
```

It appears that the issue lies in the absence of `self.cfg` definition in the [`edlclient/Library/Modules/generic.py`](https://github.com/bkerler/edl/blob/97fffcf4e3db1ea1f42d6a6b87161752dba81c7f/edlclient/Library/Modules/generic.py) file.

Upon further investigation, I found a reference to `SECTOR_SIZE_IN_BYTES` in `Library/Modules/oneplus.py`, which suggests that it should be equal to `4096`.

To resolve the issue, I manually edited the code and replaced `self.cfg.SECTOR_SIZE_IN_BYTES` with `4096`, which allowed me to successfully unlock my phone. 

As I have limited understanding of the codebase, I'm not sure if I should open a pull request to correct it or if there is a better way to handle this situation.

If you require any additional tests or information to address this issue, please don't hesitate to ask.

**Comment by AntoineMahe** [comment]
closed by https://github.com/bkerler/edl/pull/474
