### ISSUE TITLE
AttributeError: type object 'req' has no attribute 'version'

### ISSUE THREAD

**Issue by adeveloper79** [bkerler/edl#467]
tried on my zenfone 9 and it gave this error 

`E:\edl> python edl --serial --loader=zenfone9_firehose_ddr.elf
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2023.
main
main - [LIB]: Please first install libusb_win32 driver from Zadig
main - Using loader zenfone9_firehose_ddr.elf ...
main - Waiting for the device
Detected 0x5c6:0x9008 device at: COM8
main - Device detected :)
DeviceClass - Warning !
main - Mode detected: sahara
Traceback (most recent call last):
  File "E:\edl\edl", line 386, in <module>
    base.run()
  File "E:\edl\edl", line 294, in run
    version = conninfo["data"].version
              ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'req' has no attribute 'version'`

i tried on my other older devices too it had same error

**Comment by chandanroksjsr** [comment]
did you manage to solve this?

**Comment by adeveloper79** [comment]
> did you manage to solve this?

sadly no

**Comment by filipe-maia** [comment]
Same as:
https://github.com/bkerler/edl/issues/508
