### ISSUE TITLE
XT2135-2 Motorola G60  -A ttributeError: type object 'req' has no attribute 'version'

### ISSUE THREAD

**Issue by chandanroksjsr** [bkerler/edl#470]
my device is XT-2135-2 Motorola G60 
i am trying to enable oemunlock, the device is locked bootloader state and with invalid os i am getting the following error stack trace
please help me out what am i doing wrong here and how do i fix this.
```
root@chandu:/home/chandu/edl# edl modules oemunlock enable --loader=sahara --debugmode
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2023.
main - Using loader sahara ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: ['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.62\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 386, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 289, in run\n    conninfo = self.doconnect(loop)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 219, in doconnect\n    resp = self.sahara.connect()\n']
DeviceClass
DeviceClass - [LIB]: TX:<?xml version="1.0" ?><data><nop /></data>
DeviceClass
DeviceClass - [LIB]: read:0x10
DeviceClass
DeviceClass - [LIB]: ['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.62\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 386, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 289, in run\n    conninfo = self.doconnect(loop)\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 219, in doconnect\n    resp = self.sahara.connect()\n', '  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/edlclient/Library/sahara.py", line 135, in connect\n    res = self.cdc.read(timeout=1)\n']
DeviceClass
DeviceClass - [LIB]: RX:04000000100000000d00000001000000
main - Mode detected: sahara
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.62', 'edl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 386, in <module>
    base.run()
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 294, in run
    version = conninfo["data"].version
AttributeError: type object 'req' has no attribute 'version'
```

**Comment by dcboy** [comment]
ther is the same for me, how to resolve?
