### ISSUE TITLE
randomly gets stuck on windows?

### ISSUE THREAD

**Issue by Appleisbest** [bkerler/edl#52]
Hi, 

When I try dumping any partition, sometimes it succeeds, but most of the time it gets stuck at a random percent. Usually it stops at 99% but I have seen it get stuck at 55% or something. I am running windows 10.

**Comment by bkerler** [comment]
This might happen for many reasons, but all normally are due to usb timeouts. Try a different usb hub. If it still fails, just run with --debugmode and send me the log to see how we might be able to fix it.

**Comment by Appleisbest** [comment]
I also tried it on Mac OS and for a similar problem... At soon as I get to my machine I'll send you the log

**Comment by kercre123** [comment]
I never experienced full halts, but sometimes the transfer would become painfully slow near the middle and I have to CTRL+C, disconnect/reconnect the device, and try again. It only happens to me on Windows.

**Comment by Appleisbest** [comment]
[edl master log.txt](https://github.com/bkerler/edl/files/6023286/edl.master.log.txt)

Here is the log. Similar to kercre123's issue, it seems like it freezes or goes painfully slow near the middle or end...I have to hit ctrl + c to stop it. (I hit ctrl + c at the end so the log may show a keyboard interrupt erro.r)

**Comment by bkerler** [comment]
Commit a5fdf09 might solve this issue. Please try :)

**Comment by Appleisbest** [comment]
Now I just get this from powershell

edl-a5fdf09c93110a1533ce30b619dd3f0b43bc55a7> python3 edl.py r boot_a boot.img --loader C:\Users\Dylan\Desktop\prog_emmc_firehose_8909.mbn                                                                            Qualcomm Sahara / Firehose Client V3.2 (c) B.Kerler 2018-2021.
main - Using loader C:\Users\Dylan\Desktop\prog_emmc_firehose_8909.mbn ...
main - Waiting for the device
Traceback (most recent call last):
  File "C:\Users\Dylan\Desktop\edl-a5fdf09c93110a1533ce30b619dd3f0b43bc55a7\Library\usblib.py", line 247, in connect
    if self.device.is_kernel_driver_active(self.interface):
  File "C:\Users\Dylan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\core.py", line 1100, in is_kernel_driver_active
    interface)
  File "C:\Users\Dylan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\backend\libusb0.py", line 623, in is_kernel_driver_active
    raise NotImplementedError(self.is_kernel_driver_active.__name__)
NotImplementedError: is_kernel_driver_active

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "edl.py", line 360, in <module>
    base.run()
  File "edl.py", line 257, in run
    mode, resp = self.doconnect(loop, mode, resp)
  File "edl.py", line 155, in doconnect
    self.cdc.connected = self.cdc.connect()
  File "C:\Users\Dylan\Desktop\edl-a5fdf09c93110a1533ce30b619dd3f0b43bc55a7\Library\usblib.py", line 250, in connect
    except Exception(UsbClass) as e:
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by bkerler** [comment]
Looks like you're still using the old code :) Try to do a git pull and retry.

**Comment by Appleisbest** [comment]
I downloaded the zip from here, and it gave me the exact same error.

**Comment by bkerler** [comment]
Can you retry using mac ? The upper problem seems to be due to improper kernel driver (try to use zadig under windows)

**Comment by Appleisbest** [comment]
I can try as soon as I get to my Apple machine. I finally booted Ubuntu Linux and this worked fine.
Is there any way how this can be fixed for windows?

**Comment by bkerler** [comment]
Yes, I'm already working on it :)

**Comment by bkerler** [comment]
Can you please try the last commit ?

**Comment by kercre123** [comment]
> Can you please try the last commit ?

Currently using the latest commit on a Windows laptop. Getting the same error as shown above (NotImplementedError: is_kernel_driver_active). I did use Zadig to switch the driver to libusb-win32.

Here is the log and full error
[log.txt](https://github.com/bkerler/edl/files/6094921/log.txt)

```
C:\Users\Wire\Desktop\edl-master>py edl.py --loader=8909.mbn secureboot --debugmode
Qualcomm Sahara / Firehose Client V3.2 (c) B.Kerler 2018-2021.
main - Using loader 8909.mbn ...
main - Waiting for the device
UsbClass
UsbClass - [LIB]: ←[95m  CONFIGURATION 1: 2 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x20 (32 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :    0x1 (2 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x0
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0←[0m
Traceback (most recent call last):
  File "C:\Users\Wire\Desktop\edl-master\Library\usblib.py", line 247, in connect
    if self.device.is_kernel_driver_active(self.interface):
  File "C:\Users\Wire\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 1098, in is_kernel_driver_active
    return self._ctx.backend.is_kernel_driver_active(
  File "C:\Users\Wire\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\backend\libusb0.py", line 623, in is_kernel_driver_active
    raise NotImplementedError(self.is_kernel_driver_active.__name__)
NotImplementedError: is_kernel_driver_active

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wire\Desktop\edl-master\edl.py", line 360, in <module>
    base.run()
  File "C:\Users\Wire\Desktop\edl-master\edl.py", line 257, in run
    mode, resp = self.doconnect(loop, mode, resp)
  File "C:\Users\Wire\Desktop\edl-master\edl.py", line 155, in doconnect
    self.cdc.connected = self.cdc.connect()
  File "C:\Users\Wire\Desktop\edl-master\Library\usblib.py", line 250, in connect
    except Exception(UsbClass) as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by bkerler** [comment]
@kercre123 looks like you're still using the old version. Please retry and make sure you're using commit 2b9162a :)

**Comment by kercre123** [comment]
Now it is working! I'll try a few writes and reads tomorrow to see if it still gets stuck or slows down in the middle.

**Comment by Appleisbest** [comment]
Wait how do you get the latest commit then...I think I'm confused.

**Comment by bkerler** [comment]
@Appleisbest As I have multiple people reporting things not working, although being fixed, I think the zip download at github might be broken (or the browser cache maybe). Always use git pull to get the latest commit.

**Comment by Appleisbest** [comment]
Still gets error, even with the latest commit

**Comment by bkerler** [comment]
Ok, this means it still overreads. Can you upload the gpt and let me know which partition you try to read ?

**Comment by Appleisbest** [comment]
Is this what you mean by uploading the gpt??? 

I am trying to dump the boot, aboot, and system partitons

Parsing Lun 0:

GPT Table:
-------------
modem:               Offset 0x0000000004000000, Length 0x0000000004200000, Flags 0x00000010, UUID 188146cc-eefc-472c-2159-bb73be85de7f, Type EFI_BASIC_DATA
DDR:                 Offset 0x0000000008200000, Length 0x0000000000008000, Flags 0x00000010, UUID 220ddacf-1b96-ae46-ecff-9e3aaa5a27b5, Type 0x20a0c19c
fsg:                 Offset 0x0000000008208000, Length 0x0000000000180000, Flags 0x00000010, UUID 38188473-a617-87ff-cbee-f4d02bfab014, Type 0x638ff8e2
sec:                 Offset 0x0000000008388000, Length 0x0000000000004000, Flags 0x00000010, UUID f19351c8-3110-3767-2001-f6c29bfca40c, Type 0x303e6ac3
boot:                Offset 0x000000000838c000, Length 0x0000000002000000, Flags 0x00000010, UUID 0efcbc03-a1a3-cf39-2d05-b06ab2af9ff8, Type 0x20117f86
system:              Offset 0x000000000a38c000, Length 0x000000004b000000, Flags 0x00000010, UUID 0e92b789-606f-c946-8b5c-9be28a1df926, Type 0x97d7b011
persist:             Offset 0x000000005538c000, Length 0x0000000002000000, Flags 0x00000010, UUID 07f11fc5-b6a4-6301-f24d-fa9b862ffef4, Type 0x6c95e238
cache:               Offset 0x000000005738c000, Length 0x0000000006e00000, Flags 0x00000010, UUID 4362453f-8b8e-0614-cbdc-e3508c04404c, Type 0x5594c694
recovery:            Offset 0x000000005e18c000, Length 0x0000000002000000, Flags 0x00000010, UUID a5c73baa-2ced-6e26-cad7-b2534dd325f6, Type 0x9d72d4e4
devinfo:             Offset 0x000000006018c000, Length 0x0000000000100000, Flags 0x00000010, UUID fd38352a-42a5-e6ff-90b8-1f45a7a31d97, Type 0x1b81e7e6
cmnlib:              Offset 0x000000006028c000, Length 0x0000000000040000, Flags 0x00000010, UUID f6cc2a16-6814-0578-00aa-bf9724fb348c, Type 0x73471795
cmnlibbak:           Offset 0x00000000602cc000, Length 0x0000000000040000, Flags 0x00000010, UUID b1c7607d-b276-5294-1183-632f37cc9a63, Type 0x73471795
keymaster:           Offset 0x000000006030c000, Length 0x0000000000080000, Flags 0x00000010, UUID 51565d20-6014-dd16-179d-3a3ffc927e60, Type 0xe8b7cf6e
keymasterbak:        Offset 0x000000006038c000, Length 0x0000000000080000, Flags 0x00000010, UUID 7fbb1712-ac67-2cc3-1967-b9dd623cc138, Type 0xe8b7cf6e
sbl1:                Offset 0x0000000064000000, Length 0x0000000000080000, Flags 0x00000000, UUID 2e3e14a2-4fd7-7e35-4604-3cea572e4bf7, Type 0xdea0ba2c
sbl1bak:             Offset 0x0000000064080000, Length 0x0000000000080000, Flags 0x00000000, UUID f46d3197-bf9e-7560-6a18-6b9428aea64c, Type 0xdea0ba2c
aboot:               Offset 0x0000000064100000, Length 0x0000000000100000, Flags 0x00000000, UUID 198c5ae5-72c3-6f31-11e6-2df9db988276, Type 0x400ffdcd
abootbak:            Offset 0x0000000064200000, Length 0x0000000000100000, Flags 0x00000000, UUID 533cd4a3-76fa-222c-a910-32795cadf07d, Type 0x400ffdcd
rpm:                 Offset 0x0000000064300000, Length 0x0000000000080000, Flags 0x00000000, UUID 1f381217-734f-8c79-3d57-ae5dc0f590eb, Type 0x98df793
rpmbak:              Offset 0x0000000064380000, Length 0x0000000000080000, Flags 0x00000000, UUID 53488b48-cecf-2c95-1dc5-bda2c6a4751b, Type 0x98df793
tz:                  Offset 0x0000000064400000, Length 0x0000000000200000, Flags 0x00000000, UUID 4677f365-2c47-0d26-d95b-fb49930fd92e, Type 0xa053aa7f
tzbak:               Offset 0x0000000064600000, Length 0x0000000000200000, Flags 0x00000000, UUID eabe37d9-31da-612c-f73a-495ca4e7886b, Type 0xa053aa7f
devcfg:              Offset 0x0000000064800000, Length 0x0000000000040000, Flags 0x00000000, UUID 5cbe4153-6ec7-79b3-c20c-0b8c231f17db, Type 0xf65d4b16
apdp:                Offset 0x0000000064840000, Length 0x0000000000040000, Flags 0x00000000, UUID b90459c9-12b1-969b-bd6b-e1ed5e1c4420, Type 0xe6e98da2
pad:                 Offset 0x0000000064880000, Length 0x0000000000100000, Flags 0x00000000, UUID c7d579d0-bcbd-ea1a-0dd3-1a800844e87c, Type EFI_BASIC_DATA
modemst1:            Offset 0x0000000064980000, Length 0x0000000000180000, Flags 0x00000000, UUID 0c39a86d-8a21-5659-33f5-b69601c33d19, Type 0xebbeadaf
modemst2:            Offset 0x0000000064b00000, Length 0x0000000000180000, Flags 0x00000000, UUID 7657f70c-5acd-7d6a-c8fe-610f4dd3bbd7, Type 0xa288b1f
misc:                Offset 0x0000000064c80000, Length 0x0000000000800000, Flags 0x00000000, UUID 8ead89a6-5ed2-0aa5-aac7-c52f6a997e62, Type 0x82acc91f
fsc:                 Offset 0x0000000065480000, Length 0x0000000000000400, Flags 0x00000000, UUID 792c3c95-fa58-4b1a-edd7-9522ca838da9, Type 0x57b90a16
ssd:                 Offset 0x0000000065480400, Length 0x0000000000002000, Flags 0x00000000, UUID 3dcf7fd5-9680-310e-f39e-5b39de3e6022, Type 0x2c86e742
splash:              Offset 0x0000000065482400, Length 0x0000000000a00000, Flags 0x00000000, UUID 1ee2ba29-d13b-5e75-bc72-e18a66de143c, Type 0x20117f86
keystore:            Offset 0x0000000065e82400, Length 0x0000000000080000, Flags 0x00000000, UUID 4bc6da4b-9a01-dd36-3a82-dddeca52c8f0, Type 0xde7d4029
oem:                 Offset 0x0000000065f02400, Length 0x0000000000800000, Flags 0x00000000, UUID d6710f0f-89a1-03e5-a9f1-38edaadfc41f, Type 0x7db6ac55
prodinfo:            Offset 0x0000000066702400, Length 0x0000000000001000, Flags 0x00000000, UUID 9ad7ead4-6bca-5070-e8a7-daf3a57f7cae, Type 0x21130059
prodinfo2:           Offset 0x0000000066703400, Length 0x0000000000001000, Flags 0x00000000, UUID 4e5b4bc7-61b6-0986-eb54-a4321ad70b50, Type 0xbc3c23ce
config:              Offset 0x0000000066704400, Length 0x0000000000080000, Flags 0x00000000, UUID de00177b-8c05-1b68-3be0-7b3fdf7a9bc6, Type 0x91b72d4d
vendor:              Offset 0x0000000066784400, Length 0x000000000fa00000, Flags 0x00000000, UUID f76d078a-8a7e-aa19-3f20-0e334dd00edc, Type 0x3c160a98
userdata:            Offset 0x0000000076184400, Length 0x000000015be77a00, Flags 0x00000000, UUID f0844577-c3d4-973c-0808-0ce0ed11afbb, Type 0x1b81e7e6

Total disk size:0x00000001d2000000, sectors:0x0000000000e90000

**Comment by bkerler** [comment]
Please try the latest commit (just uploaded). Hopefully does work now.

**Comment by nsaslavsky** [comment]
I am seeing this problem when dumping the userdata partition (all of the others one work great) it constistently gets stuck at the very end, but the exact sector varies a bit. Here is a gist with the log file and gpt https://gist.github.com/nsaslavsky/f801c849924d2a9d043de9ad948bb5da I am using commit 59bf655 (the latest as of writing this).

**Comment by bkerler** [comment]
That might be a problem of the usb port in windows, trying to to it in low power state. Please try the latest commit and usbdk driver with stock qualcomm driver to see if that helps. Otherwise try to disable power saving for the usb port.

**Comment by bkerler** [comment]
I've just increased the timeout limit, which might solve this issue.

**Comment by Appleisbest** [comment]
Ok, I will try it.

**Comment by kim12355** [comment]
i tried latest commit and it do nothing after device connected....
how about run it while partition manager on qfil running? (but qfil not recognize usbk driver)
maybe it solve.

**Comment by momords** [comment]
> I never experienced full halts, but sometimes the transfer would become painfully slow near the middle and I have to CTRL+C, disconnect/reconnect the device, and try again. It only happens to me on Windows.

How to run edl on windows?   It always says command not found etc.
