### ISSUE TITLE
how to fix this error ?

### ISSUE THREAD

**Issue by AliRazaManzoor** [bkerler/edl#527]
C:\Users\ali\Desktop\edl>python edl --serial printgpt
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2023.
main
main - [LIB]: ←[33mPlease first install libusb_win32 driver from Zadig←[0m
main - Trying with no loader given ...
main - Waiting for the device
Detected 0x5c6:0x9008 device at: COM6
main - Device detected :)
DeviceClass - Warning !
main - Mode detected: sahara
Traceback (most recent call last):
  File "C:\Users\ali\Desktop\edl\edl", line 387, in <module>
    base.run()
  File "C:\Users\ali\Desktop\edl\edl", line 295, in run
    version = conninfo["data"].version
AttributeError: type object 'req' has no attribute 'version'

**Comment by ElectroBoy404NotFound** [comment]
You need to fix a few things:
1. You need to install libusb driver
2. You are using serial mode which I found to be a little unreliable atleast on my computer
3. I think you are retrying after another failed attempt with a different error

**Comment by Ko-Hi-Dev** [comment]
> C:\Users\ali\Desktop\edl>python edl --serial printgpt Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2023. main main - [LIB]: ←[33mPlease first install libusb_win32 driver from Zadig←[0m main - Trying with no loader given ... main - Waiting for the device Detected 0x5c6:0x9008 device at: COM6 main - Device detected :) DeviceClass - Warning ! main - Mode detected: sahara Traceback (most recent call last): File "C:\Users\ali\Desktop\edl\edl", line 387, in base.run() File "C:\Users\ali\Desktop\edl\edl", line 295, in run version = conninfo["data"].version AttributeError: type object 'req' has no attribute 'version'

Download

https://zadig.akeo.ie/

And when it seems qusb install the driver. 

It worked for me
