### ISSUE TITLE
./edl rf unavailable on NAND devices

### ISSUE THREAD

**Issue by ghost** [bkerler/edl#546]
```
(venv) root@localhost ~/edl # ./edl --memory nand --loader=Loaders/qualcomm/factory/mdm9x07/000480e100000000_cc3153a80293939b_fhprg_9x07.mbn rf ec20.bin
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2023.
main - Using loader Loaders/qualcomm/factory/mdm9x07/000480e100000000_cc3153a80293939b_fhprg_9x07.mbn ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
main - Mode detected: firehose
Progress: |██████████| 100.0% Scanning (Sector 0x400 of 0x400, ) 0.00 MB/s                                                                                                            
Traceback (most recent call last):
  File "/root/edl/./edl", line 393, in <module>
    base.run()
  File "/root/edl/./edl", line 385, in run
    if not fh.handle_firehose(cmd, options):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/edl/edlclient/Library/firehose_client.py", line 352, in handle_firehose
    if self.get_storage_info():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/edl/edlclient/Library/firehose_client.py", line 184, in get_storage_info
    for info in storageinfo:

```

**Comment by RenateUSB** [comment]
Try XDA.
