### ISSUE TITLE
fhloaderparse examples Loaders (fails with library issue)

### ISSUE THREAD

**Issue by digitui** [bkerler/edl#552]
When running fhloaderparse examples Loaders under Ubuntu it gives the following error.

```
fhloaderparse examples Loaders
Traceback (most recent call last):
  File "/usr/local/bin/fhloaderparse", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.62', 'fhloaderparse')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/fhloaderparse", line 16, in <module>
    from Library.utils import elf
ModuleNotFoundError: No module named 'Library'
```

**Comment by digitui** [comment]
use ./fhloaderparse
