### ISSUE TITLE
Issues when running edl

### ISSUE THREAD

**Issue by cuynu** [bkerler/edl#563]
I getting this error when trying to run edl commands after firehose loader is loaded to device
It's still works on my old installation, but after os reinstall it doesn't work anymore.

Errors when trying to use edl commands after firehose loaders is loaded : 
```
[cuynu@cuynu-acer ~]$ edl --debugmode
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: USB Overflow
DeviceClass
DeviceClass - [LIB]: [Errno 110] Operation timed out
DeviceClass
DeviceClass - [LIB]: [Errno 110] Operation timed out
DeviceClass
DeviceClass - [LIB]: [Errno 110] Operation timed out
DeviceClass
DeviceClass - [LIB]: read:0x59
DeviceClass
DeviceClass - [LIB]: ['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.62\', \'edl\')\n', '  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 672, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1472, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/EGG-INFO/scripts/edl", line 393, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/EGG-INFO/scripts/edl", line 290, in run\n    conninfo = self.doconnect(loop)\n', '  File "/usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/EGG-INFO/scripts/edl", line 222, in doconnect\n    resp = self.sahara.connect()\n', '  File "/usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/edlclient/Library/sahara.py", line 136, in connect\n    res = self.cdc.read(timeout=1)\n']
DeviceClass
DeviceClass - [LIB]: RX:<?xml version="1.0" encoding="UTF-8" ?>
DeviceClass
DeviceClass - [LIB]: RX:<data>
DeviceClass
DeviceClass - [LIB]: RX:<log value="INFO: firmwarewrite" /></data>
main - Mode detected: firehose
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.62', 'edl')
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/EGG-INFO/scripts/edl", line 393, in <module>
    base.run()
  File "/usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/EGG-INFO/scripts/edl", line 295, in run
    version = conninfo.get("data").version
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'version'
```

If i run command directly without load firehose manually to device first, it will works but after then, other command still throw error as above : 

```
[cuynu@cuynu-acer ~]$ edl printgpt
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Trying with no loader given ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold vol dwn + pwr, in fastboot mode connect usb.
        Run "./fastpwn oem edl".
main - Other:  Run "adb reboot edl".

...main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
Version 0x2
------------------------
HWID:              0x0008b0e100310000 (MSM_ID:0x0008b0e1,OEM_ID:0x0031,MODEL_ID:0x0000)
CPU detected:      "SDM845"
PK_HASH:           0x1030cd12ce708f29d6914d7529df75149d8ef91c27daf0e1f84b90f4b707329a
Serial:            0xecab9722

sahara - Found loader: /usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/edlclient/../Loaders/LG/6000000000010000_1030cd12ce708f29_fhprg.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/edlclient/../Loaders/LG/6000000000010000_1030cd12ce708f29_fhprg.bin ...
sahara - 64-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose - INFO: Binary build date: May  8 2018 @ 11:45:06
firehose - INFO: Binary build date: May  8 2018 @ 11:45:06 
firehose - INFO: Chip serial num: 3970668322 (0xecab9722)
firehose - INFO: Supported Functions (14):
firehose - INFO: program
firehose - INFO: read
firehose - INFO: nop
firehose - INFO: patch
firehose - INFO: configure
firehose - INFO: setbootablestoragedrive
firehose - INFO: erase
firehose - INFO: power
firehose - INFO: firmwarewrite
firehose - INFO: getstorageinfo
firehose - INFO: benchmark
firehose - INFO: emmc
firehose - INFO: ufs
firehose - INFO: fixgpt
firehose - INFO: End of supported functions 14
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "UFS" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: Couldn't detect MaxPayloadSizeFromTargetinBytes
firehose
firehose - [LIB]: Couldn't detect TargetName
firehose - TargetName=Unknown
firehose - MemoryName=UFS
firehose - Version=1
firehose - Trying to read first storage sector...
firehose - Running configure...
firehose - Storage report:
firehose - total_blocks:15386624
firehose - block_size:4096
firehose - page_size:4096
firehose - num_physical:7
firehose - manufacturer_id:429
firehose - serial_num:2037279096
firehose - fw_version:002
firehose - mem_type:UFS
firehose - prod_name:H28S7Q302BMR
firehose_client - Supported functions:
-----------------
program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt

Parsing Lun 0:

GPT Table:
-------------
mpt:                 Offset 0x0000000000006000, Length 0x0000000002000000, Flags 0x0000000000000000, UUID da16209f-6502-6bd6-4dcc-e471f7b6b5a3, Type 0x62d9eb3b, Active False
drm:                 Offset 0x0000000002006000, Length 0x0000000000e00000, Flags 0x0000000000000000, UUID 9dc76bde-90e1-22b6-e15b-6cf15ab1595f, Type 0x89707cd8, Active False
sns:                 Offset 0x0000000002e06000, Length 0x0000000000600000, Flags 0x0000000000000000, UUID b2af8a25-dfa6-12c6-7278-b686e8cc8ba3, Type 0xbc086b59, Active False
ssd:                 Offset 0x0000000003406000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID a1700284-ebb9-fc76-0250-76196881300a, Type 0x2c86e742, Active False
persist:             Offset 0x0000000003486000, Length 0x0000000002000000, Flags 0x0000000000000000, UUID e4f25581-581b-8cee-c9c1-9b2b97669afc, Type 0x6c95e238, Active False
misc:                Offset 0x0000000005486000, Length 0x0000000000100000, Flags 0x0000000000000000, UUID 1a47653e-81bb-e18c-5592-70231f009f58, Type 0x82acc91f, Active False
ftm:                 Offset 0x0000000005586000, Length 0x0000000002000000, Flags 0x0000000000000000, UUID 1e7221ac-3ec7-0861-769a-9984f7cf7ad5, Type 0xdaa3eaac, Active False
power:               Offset 0x0000000007586000, Length 0x0000000002c00000, Flags 0x0000000000000000, UUID 691c2a9f-a723-d8fd-7843-e653acc6d048, Type 0xf28debc9, Active False
encrypt:             Offset 0x000000000a186000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID b7606d39-e780-1920-0b35-23f38734a313, Type 0x323ef595, Active False
eksst:               Offset 0x000000000a206000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID b4d2f31e-aeb2-3978-d7e8-618fd8a0e032, Type 0x45864011, Active False
rct:                 Offset 0x000000000a286000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID 923930cc-2760-8436-641a-faf385d6752c, Type 0x8ed8ae95, Active False
fota:                Offset 0x000000000a306000, Length 0x0000000000a00000, Flags 0x0000000000000000, UUID d44706de-5d85-ccd5-2387-f41445ae145b, Type 0x86a7cb80, Active False
srtc:                Offset 0x000000000ad06000, Length 0x0000000000800000, Flags 0x0000000000000000, UUID 8db26e1b-caa8-2648-112b-2d1635f998a5, Type 0xe28ad25d, Active False
pstore:              Offset 0x000000000b506000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID c2e55e9e-f186-73b4-fd4c-5e641e3fc191, Type 0x25064e1, Active False
els:                 Offset 0x000000000b706000, Length 0x0000000001000000, Flags 0x0000000000000000, UUID e0537ecf-5ade-607f-92b4-494e95379f93, Type 0x497da062, Active False
carrier:             Offset 0x000000000c706000, Length 0x0000000002800000, Flags 0x0000000000000000, UUID d538882c-7ba5-74e4-c720-f406ad332870, Type 0xc92a8f0a, Active False
persdata:            Offset 0x000000000ef06000, Length 0x0000000004000000, Flags 0x0000000000000000, UUID 614ce280-9a14-8fe8-3920-a7d29865e326, Type 0x6a42e2d9, Active False
oem_a:               Offset 0x0000000012f06000, Length 0x0000000000800000, Flags 0x0004000000000000, UUID c90373cb-cf81-9f71-55e8-d56044ff3da4, Type 0x66ae456f, Active True
oem_b:               Offset 0x0000000013706000, Length 0x0000000000800000, Flags 0x0000000000000000, UUID b3e15e4e-4acf-ad57-078e-8c116387b693, Type 0xe9f471e6, Active False
vendor_a:            Offset 0x0000000013f06000, Length 0x000000003e800000, Flags 0x007f000000000000, UUID 8ef02e79-e5f0-b32f-4464-d4e65f83301d, Type 0x97d7b011, Active True
vendor_b:            Offset 0x0000000052706000, Length 0x000000003e800000, Flags 0x003b000000000000, UUID 39170827-6d01-b51d-7d78-bee0c4f97635, Type 0x77036cd4, Active False
system_a:            Offset 0x0000000090f06000, Length 0x000000011b800000, Flags 0x007f000000000000, UUID d173046f-8f5f-0e7a-451c-9c5706aa9ffd, Type 0x97d7b011, Active True
system_b:            Offset 0x00000001ac706000, Length 0x000000011b800000, Flags 0x003b000000000000, UUID c90e27fb-16cd-6e6f-ab7a-c2a313c7d668, Type 0x77036cd4, Active False
OP_a:                Offset 0x00000002c7f06000, Length 0x000000001d000000, Flags 0x0004000000000000, UUID b53aa99f-fd23-ec8a-c3c8-807db69db2ff, Type 0x3f8205f3, Active True
OP_b:                Offset 0x00000002e4f06000, Length 0x000000001d000000, Flags 0x0000000000000000, UUID 68c08bcd-ce25-9118-632b-8eecb10a0792, Type 0x77036cd4, Active False
userdata:            Offset 0x0000000301f06000, Length 0x0000000baa8f4000, Flags 0x0000000000000000, UUID 9a4ed98a-f6b2-c96a-f406-61c6a10d8157, Type 0x1b81e7e6, Active False
grow:                Offset 0x0000000eac7fa000, Length 0x0000000000001000, Flags 0x0000000000000000, UUID 8948a394-fb86-532a-c05d-0713737a3387, Type 0x32bf34b8, Active False

Total disk size:0x0000000eac800000, sectors:0x0000000000eac800


Parsing Lun 1:

GPT Table:
-------------
xbl_a:               Offset 0x0000000000006000, Length 0x0000000000380000, Flags 0x10c4000000000000, UUID 6fde141a-3125-5218-9c2f-79be71d40990, Type 0xdea0ba2c, Active True
xbl_config_a:        Offset 0x0000000000386000, Length 0x0000000000020000, Flags 0x00c4000000000000, UUID 9887ee7e-e6ca-9c55-fedd-5e91a33208e7, Type 0x5a325ae4, Active True

Total disk size:0x0000000000800000, sectors:0x0000000000000800


Parsing Lun 2:

GPT Table:
-------------
xbl_b:               Offset 0x0000000000006000, Length 0x0000000000380000, Flags 0x10c0000000000000, UUID 9ebbb48e-477b-9f68-d641-85759e7ff8b0, Type 0xdea0ba2c, Active False
xbl_config_b:        Offset 0x0000000000386000, Length 0x0000000000020000, Flags 0x0040000000000000, UUID ef29e6e5-ca8b-4e0f-fe9a-46ef8807d5ec, Type 0x5a325ae4, Active False

Total disk size:0x0000000000800000, sectors:0x0000000000000800


Parsing Lun 3:

GPT Table:
-------------
ALIGN_TO_128K_1:     Offset 0x0000000000006000, Length 0x000000000001a000, Flags 0x1000000000000000, UUID 6461e26f-cf77-94be-8a1f-5b21310efead, Type 0xfde1604b, Active False
cdt:                 Offset 0x0000000000020000, Length 0x0000000000020000, Flags 0x1000000000000000, UUID 8ffe1e06-5ec1-1096-9188-362f7a2926fa, Type 0xa19f205f, Active False
ddr:                 Offset 0x0000000000040000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID 95ce7255-18ad-f309-9a09-904ada404cae, Type 0x20a0c19c, Active False

Total disk size:0x0000000000800000, sectors:0x0000000000000800


Parsing Lun 4:

GPT Table:
-------------
aop_a:               Offset 0x0000000000006000, Length 0x0000000000080000, Flags 0x107f000000000000, UUID 9325a0a3-667d-5e50-3dff-545a840d1b5d, Type 0xd69e90a5, Active True
tz_a:                Offset 0x0000000000086000, Length 0x0000000000200000, Flags 0x107f000000000000, UUID 1dff6a1f-7843-9c05-c42a-1e06ba380469, Type 0xa053aa7f, Active True
hyp_a:               Offset 0x0000000000286000, Length 0x0000000000080000, Flags 0x007f000000000000, UUID f6e646d9-b010-3699-2c0d-00510e209288, Type 0xe1a6a689, Active True
modem_a:             Offset 0x0000000000306000, Length 0x000000000b600000, Flags 0x107f000000000000, UUID 99dc5e5e-7904-8a42-7ca9-de749f473e11, Type EFI_BASIC_DATA, Active True
mdtpsecapp_a:        Offset 0x000000000b906000, Length 0x0000000000400000, Flags 0x1004000000000000, UUID 0eb3e30a-9e49-2f53-1ad4-1a58610d6f0e, Type 0xea02d680, Active True
mdtp_a:              Offset 0x000000000bd06000, Length 0x0000000002000000, Flags 0x1004000000000000, UUID 216ca641-4120-02e5-d080-6ab7e9378250, Type 0x3878408a, Active True
abl_a:               Offset 0x000000000dd06000, Length 0x0000000000100000, Flags 0x107f000000000000, UUID de2aacb5-13d1-f056-e4a3-ffe806b7e5b1, Type 0xbd6928a1, Active True
dsp_a:               Offset 0x000000000de06000, Length 0x0000000002000000, Flags 0x1004000000000000, UUID 64a717fa-56a8-fc76-6ee6-6e7905adb2f6, Type 0x7efe5010, Active True
keymaster_a:         Offset 0x000000000fe06000, Length 0x0000000000080000, Flags 0x107f000000000000, UUID f82383dd-9e8c-d277-286c-e67d33c47264, Type 0xa11d2a7c, Active True
akmu_a:              Offset 0x000000000fe86000, Length 0x0000000000080000, Flags 0x1004000000000000, UUID 363f5122-fe62-ec96-72e7-3de72de42436, Type 0xa41f16ae, Active True
boot_a:              Offset 0x000000000ff06000, Length 0x0000000004000000, Flags 0x0077000000000000, UUID f13d75e4-a3e0-71eb-5eb8-6a1e34230c6f, Type 0x20117f86, Active True
cmnlib_a:            Offset 0x0000000013f06000, Length 0x0000000000080000, Flags 0x107f000000000000, UUID f95afead-b95f-aea7-5339-da016990475b, Type 0x73471795, Active True
cmnlib64_a:          Offset 0x0000000013f86000, Length 0x0000000000080000, Flags 0x107f000000000000, UUID a04c3132-729a-0299-11f9-d80e40d62d77, Type 0x8ea64893, Active True
devcfg_a:            Offset 0x0000000014006000, Length 0x0000000000020000, Flags 0x007f000000000000, UUID 94b7b48a-251d-c0b1-35d4-ebdc862ac2da, Type 0xf65d4b16, Active True
qupfw_a:             Offset 0x0000000014026000, Length 0x0000000000020000, Flags 0x007f000000000000, UUID c1713a24-bbc0-8958-44cb-3a21d63f1bbe, Type 0x21d1219f, Active True
laf_a:               Offset 0x0000000014046000, Length 0x0000000003000000, Flags 0x0044000000000000, UUID e961f004-d0e6-436c-9a5a-bab5de404346, Type 0x98523ec6, Active True
vbmeta_a:            Offset 0x0000000017046000, Length 0x0000000000010000, Flags 0x107f000000000000, UUID 50a6275b-8f42-8ec1-4144-d1ca42fea3b5, Type 0x4b7a15d6, Active True
dtbo_a:              Offset 0x0000000017056000, Length 0x0000000000800000, Flags 0x007f000000000000, UUID 3e7e544d-8bfe-a96f-873e-af47e8337ae4, Type 0x24d0d418, Active True
storsec_a:           Offset 0x0000000017856000, Length 0x0000000000020000, Flags 0x007f000000000000, UUID 43cff44b-1fd7-491b-74f5-4e9bccd60d0b, Type 0x2db45fe, Active True
raw_resources_a:     Offset 0x0000000017876000, Length 0x0000000000800000, Flags 0x0004000000000000, UUID 03612dcc-a5ad-db01-66b8-51d94a4b7e00, Type 0x4627ae27, Active True
sid_a:               Offset 0x0000000018076000, Length 0x0000000000080000, Flags 0x0004000000000000, UUID a41fbe9d-8529-f72b-bc66-aa0626626cb8, Type 0x4d96a5ff, Active True
aop_b:               Offset 0x00000000180f6000, Length 0x0000000000080000, Flags 0x003b000000000000, UUID baf99540-2154-f9a2-c86f-2cd62f64527a, Type 0x77036cd4, Active False
tz_b:                Offset 0x0000000018176000, Length 0x0000000000200000, Flags 0x003b000000000000, UUID 9a41008d-a673-eeaa-9008-a7d8edbc4031, Type 0x77036cd4, Active False
hyp_b:               Offset 0x0000000018376000, Length 0x0000000000080000, Flags 0x003b000000000000, UUID efc33d17-65c2-5312-6bde-8b6ce968d9a4, Type 0x77036cd4, Active False
modem_b:             Offset 0x00000000183f6000, Length 0x000000000b600000, Flags 0x103b000000000000, UUID 374c086f-b5e7-aaf0-2ff3-dd6665a17b1c, Type 0x77036cd4, Active False
mdtpsecapp_b:        Offset 0x00000000239f6000, Length 0x0000000000400000, Flags 0x103b000000000000, UUID 4e850d6b-38f0-7c04-3e41-32def0c6ffe3, Type 0x77036cd4, Active False
mdtp_b:              Offset 0x0000000023df6000, Length 0x0000000002000000, Flags 0x103b000000000000, UUID 150bc169-c93a-f299-258b-3ec0071a0e37, Type 0x77036cd4, Active False
abl_b:               Offset 0x0000000025df6000, Length 0x0000000000100000, Flags 0x103b000000000000, UUID 88267e8a-92e7-3a51-7d2a-fa88a76933b5, Type 0x77036cd4, Active False
dsp_b:               Offset 0x0000000025ef6000, Length 0x0000000002000000, Flags 0x103b000000000000, UUID 00f5f89a-31f5-4995-610a-1eae7b397968, Type 0x77036cd4, Active False
keymaster_b:         Offset 0x0000000027ef6000, Length 0x0000000000080000, Flags 0x103b000000000000, UUID 5a2eb824-5ea7-7293-c299-1c7dac39ae9a, Type 0x77036cd4, Active False
akmu_b:              Offset 0x0000000027f76000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 10568637-699d-eca7-639d-0915b8daec89, Type 0x77036cd4, Active False
boot_b:              Offset 0x0000000027ff6000, Length 0x0000000004000000, Flags 0x003b000000000000, UUID 8938135f-f42f-82ed-2e66-170469105f52, Type 0x77036cd4, Active False
cmnlib_b:            Offset 0x000000002bff6000, Length 0x0000000000080000, Flags 0x103b000000000000, UUID dc1f2ca1-198e-592c-a563-80a6fa5eb927, Type 0x77036cd4, Active False
cmnlib64_b:          Offset 0x000000002c076000, Length 0x0000000000080000, Flags 0x103b000000000000, UUID e1224493-3ca0-64fc-0380-26eadfea4bbb, Type 0x77036cd4, Active False
devcfg_b:            Offset 0x000000002c0f6000, Length 0x0000000000020000, Flags 0x003b000000000000, UUID 1268e94f-5990-2bbf-db1c-f4f90ad052eb, Type 0x77036cd4, Active False
qupfw_b:             Offset 0x000000002c116000, Length 0x0000000000020000, Flags 0x003b000000000000, UUID 8988074d-7a0b-4569-a1a7-019524168ffd, Type 0x77036cd4, Active False
laf_b:               Offset 0x000000002c136000, Length 0x0000000003000000, Flags 0x003b000000000000, UUID a80170db-10db-af7b-1720-216df2a0ac87, Type 0x77036cd4, Active False
vbmeta_b:            Offset 0x000000002f136000, Length 0x0000000000010000, Flags 0x103b000000000000, UUID 932c3c3c-173f-a74d-f6cb-8c372b1e3d77, Type 0x77036cd4, Active False
dtbo_b:              Offset 0x000000002f146000, Length 0x0000000000800000, Flags 0x003b000000000000, UUID 0a394a07-9301-62b0-ea7b-40c1f2c36edb, Type 0x77036cd4, Active False
storsec_b:           Offset 0x000000002f946000, Length 0x0000000000020000, Flags 0x003b000000000000, UUID f62155ed-1c7c-7e92-c845-abde45b8de67, Type 0x77036cd4, Active False
raw_resources_b:     Offset 0x000000002f966000, Length 0x0000000000800000, Flags 0x0000000000000000, UUID 0c51bdb3-507b-7260-b3f8-62be5b9d081b, Type 0x77036cd4, Active False
sid_b:               Offset 0x0000000030166000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID 4fabce21-f290-33cc-4d36-ee22ed2c642d, Type 0x77036cd4, Active False
sec:                 Offset 0x00000000301e6000, Length 0x0000000000040000, Flags 0x1000000000000000, UUID e7c44619-49b9-b3d1-4dda-54776e26a20c, Type 0x303e6ac3, Active False
devinfo:             Offset 0x0000000030226000, Length 0x0000000000040000, Flags 0x1000000000000000, UUID 7e2c6e0d-5aee-4f28-0290-6716dff1bbe8, Type 0x65addcf4, Active False
dip:                 Offset 0x0000000030266000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID cb82c409-1811-1fd1-ba09-9241380afee1, Type 0x4114b077, Active False
apdp:                Offset 0x0000000030366000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID 240aba42-596e-0f4f-2d78-abd14bbde832, Type 0xe6e98da2, Active False
msadp:               Offset 0x00000000303e6000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID b99396f6-80fe-6fc8-4774-6929657deeb2, Type 0xed9e8101, Active False
spunvm:              Offset 0x0000000030466000, Length 0x0000000000800000, Flags 0x0000000000000000, UUID 8c0e0237-e4a7-db2f-7afa-f1af4dc00c20, Type 0xe42e2b4c, Active False
limits:              Offset 0x0000000030c66000, Length 0x0000000000001000, Flags 0x1000000000000000, UUID c18d8903-8e3e-f65d-0e42-5716365b08e6, Type 0x10a0c19c, Active False
toolsfv:             Offset 0x0000000030c67000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID ea50844a-0372-c6c3-e40d-e7a0b080ca50, Type 0x97745aba, Active False
logfs:               Offset 0x0000000030d67000, Length 0x0000000000800000, Flags 0x0000000000000000, UUID e6f28376-f609-1041-30a4-7884094e9a40, Type 0xbc0330eb, Active False
sti:                 Offset 0x0000000031567000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID 13e0fdd1-621c-d2c9-27ae-2578e14b3fa8, Type 0xaa9a5c4c, Active False
logdump:             Offset 0x0000000031767000, Length 0x0000000004000000, Flags 0x0000000000000000, UUID 54b06d3a-a494-2da6-93e8-9e77488f270d, Type 0x5af80809, Active False

Total disk size:0x0000000036000000, sectors:0x0000000000036000


Parsing Lun 5:

GPT Table:
-------------
ALIGN_TO_128K_2:     Offset 0x0000000000006000, Length 0x000000000001a000, Flags 0x1000000000000000, UUID f3320dcc-5064-779e-a17f-cce3d96061b3, Type 0x6891a3b7, Active False
modemst1:            Offset 0x0000000000020000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID 1fe5b8a5-3d10-e4d6-7d7d-7ad6bdf156ff, Type 0xebbeadaf, Active False
modemst2:            Offset 0x0000000000220000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID 94c37386-2a65-5c19-7b02-be1d7c00c7ba, Type 0xa288b1f, Active False
fsg:                 Offset 0x0000000000420000, Length 0x0000000000200000, Flags 0x1000000000000000, UUID 73e3bf2a-9d5a-4d3a-3972-14676dbd36a0, Type 0x638ff8e2, Active False
fsc:                 Offset 0x0000000000620000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID 1fde8c79-f7a2-2e5e-49a6-454f2e0c70b6, Type 0x57b90a16, Active False

Total disk size:0x0000000000800000, sectors:0x0000000000000800


Parsing Lun 6:

GPT Table:
-------------
frp:                 Offset 0x0000000000006000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID a4c601cb-c837-782d-33e8-1daf7fa15247, Type 0x91b72d4d, Active False

Total disk size:0x0000000000800000, sectors:0x0000000000000800

[cuynu@cuynu-acer ~]$ edl
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.62', 'edl')
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/EGG-INFO/scripts/edl", line 393, in <module>
    base.run()
  File "/usr/local/lib/python3.11/site-packages/edlclient-3.62-py3.11.egg/EGG-INFO/scripts/edl", line 295, in run
    version = conninfo.get("data").version
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'version'
```

**Comment by dgoodwin430** [comment]
This solved the same issue for me. Thanks!
