### ISSUE TITLE
No backend (libusb issue?)

### ISSUE THREAD

**Issue by ThunderStud613** [bkerler/edl#566]
```
~/edl $ python edl printgpt --loader=prog_ufs_firehose_8998_ddr.elf
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Using loader prog_ufs_firehose_8998_ddr.elf ...
main - Waiting for the device
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/edl/edl", line 393, in <module>
    base.run()
  File "/data/data/com.termux/files/home/edl/edl", line 290, in run
    conninfo = self.doconnect(loop)
               ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/edl/edl", line 202, in doconnect
    self.cdc.connected = self.cdc.connect(portname=self.portname)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/edl/edlclient/Library/Connection/usblib.py", line 220, in connect
    devices = usb.core.find(find_all=True, backend=self.backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/usb/core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
~/edl $
```

Am I missing anything here? I didn't see in the readme about needing to add anything for a backend unless I'm blind. This sucks because I thought I was gonna get to restore my S8. Unfortunately not

EDIT:
I forgot since I'm doing this in Termux I had to setup my environment differently. I was able to resolve this issue. My apologies for this folks!

**Comment by Light034** [comment]
Hey @ThunderStud613, I'm having the same issue, I need to use EDL through termux as I don't have access to a PC right now, could you elaborate how you resolved this issue? And if you got it to work?
