### ISSUE TITLE
Device detected but nothing happens

### ISSUE THREAD

**Issue by DaieBotC418** [bkerler/edl#588]
I'm using a huawei Y7 Prime 2019 trying to unlock the bootloader on windows using edl but this happens

C:\a\edl>edl
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)

C:\a\edl>

nothin more happens(sorry for my bad english)

**Comment by RenateUSB** [comment]
Why not give it a command like `edl printgpt`

**Comment by prj** [comment]
Same issue here and this does not change anything.

This is with libusb.

If I try with serial port I get this:
Traceback (most recent call last):
  File "C:\tmp\MC7010\edl-master\edl", line 393, in <module>
    base.run()
  File "C:\tmp\MC7010\edl-master\edl", line 293, in run
    version = conninfo.get("data").version
AttributeError: type object 'req' has no attribute 'version'

**Comment by prj** [comment]
Solution is to install the WinUSB driver with Zadig.

**Comment by arkdamenen** [comment]
> Same issue here and this does not change anything.
> 
> This is with libusb.
> 
> If I try with serial port I get this: Traceback (most recent call last): File "C:\tmp\MC7010\edl-master\edl", line 393, in base.run() File "C:\tmp\MC7010\edl-master\edl", line 293, in run version = conninfo.get("data").version AttributeError: type object 'req' has no attribute 'version'

I have absolutely the same error.
I have tried to install "WinUSB (v6.1.7600.16385)" and "libusb-win32 (v1.2.7.3)" drivers through the Zadig GUI program, in both cases still the same problem.
How did you manage to fix, @prj?

**Comment by arkdamenen** [comment]
I have had absolutely the same error.
I have tried to install "WinUSB (v6.1.7600.16385)". For whatever reason, it would not work directly (would be empty), but only after a restart of Android device in EDL mode.

OS is Windows 10, USB port is 3.0.

**Comment by Dinlay1** [comment]
My computer: Linux pop-os 6.9.3-76060903-generic ....  x86_64 x86_64 x86_64 GNU/Linux
Smartphone: LG G6 H870 with latest (last) Android 9
EDL mode with shortcut on motherboard
>lsusb:  Bus 003 Device 017: ID 05c6:9008 Qualcomm, Inc. Gobi Wireless Modem (QDL mode)

I got the same behaviour as mentioned above:
"main - Device detected" 

In Visual Studio code I followed the debugging till ...
edl/edlclient/Library/Connection/usblib.py:391    as in line 395 it throws the "usb.core.USBError" exception with message "Operation timed out".
I changed the timeout to 1000 msec with the same result

As I think this happens before any firehose loader is used ?!  

How to continue ?!

**Comment by Dinlay1** [comment]
Maybe the reason was low charge of the device ?! I charged it up to 100%
Now I get:

pete@pop-os:~/edl$ edl

<code>
/usr/local/bin/edl:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('edlclient==3.62', 'edl')
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
Version 0x2
------------------------
HWID:              0x0005f0e100310000 (MSM_ID:0x0005f0e1,OEM_ID:0x0031,MODEL_ID:0x0000)
CPU detected:      "MSM8996Pro"
PK_HASH:           0x2cf7619a278d26073f7eea79bb7f4b7949c221487fea058ea072cffe38ce1496
Serial:            0xe1b27ffc

sahara - Detected loader: /usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/LG/0005f0e100310000_2cf7619a278d2607_fhprg_peek.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /usr/local/lib/python3.10/dist-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/LG/0005f0e100310000_2cf7619a278d2607_fhprg_peek.bin ...
sahara - 64-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
</code>
pete@pop-os:~/edl$

**Comment by trekronor** [comment]
Well, on my Xiaomi, we need battery disconnected for EDL mode.
On Linux it can reply with printgpt results, but it does disconnect and various errors (some might be loader related).

Tried many solutions on Win 10 on two (AMD) PC but never get results, program just end after detection.
Seem to be a Win10/libusb issue maybe testing more versions can solve it. But I'm so tired of this.....

**Comment by Dinlay1** [comment]
Sounds cumbersome and annoying :-(

I had some problems under Linux with **edl**; device busy, or "restart phone" advice due to some errors ...

As I realized that a possible reason for my problems was too less charge on my mobile, I changed to Windows (11)
and established a stable connection via  _QPST/QFIL_.
But I explicitly use a firehose (obviously the right one) that I found after some research

**Comment by RenateUSB** [comment]
> Well, on my Xiaomi, we need battery disconnected for EDL mode.

Mmm, it's fine to do stuff like disconnecting the battery when testing for the correct Firehose.
It makes rebooting easy and doing nothing you're only drawing ~100 mA or so.
But for reliability or flashing there are going to be some peak currents that want a battery.

**Comment by trekronor** [comment]
> > Well, on my Xiaomi, we need battery disconnected for EDL mode.
> 
> Mmm, it's fine to do stuff like disconnecting the battery when testing for the correct Firehose. It makes rebooting easy and doing nothing you're only drawing ~100 mA or so. But for reliability or flashing there are going to be some peak currents that want a battery.

Yep. 
Hey thanks Renate, I found your advice to always keep the cable connected, shorting test points and long-press power while keep on testing loaders worked for me. 
Can now backup and flash partitions. 
I also fed power to USB from another source, for stability, just in case.

**Comment by masabavision-gif** [comment]
On android 15 it keeps saying VIP enabled any solution?

**Comment by mvincm** [comment]
I had the same! Try to switch winusb->ibusb and libusb->winusb. Works for my. Once on libusb and second time on winusb. Don't try to understand why ;) Just use it ;)
