### ISSUE TITLE
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error

### ISSUE THREAD

**Issue by Y2K-x** [bkerler/edl#6]
Heya! Been trying to use this tool on a OnePlus 7 Pro to little success. I've gotten the libusb filter driver installed over the QC 9008 port and everything however I'm unable to read out anything from the device, as I get this error every attempt.
```
>python3 edl.py -memory ufs -r devinfo devinfo.bin

Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2019.


Trying with loaders in Loader directory ...
Waiting for the device
Device detected :)
Mode detected: Sahara

------------------------
HWID:              0x000a50e100514985 (MSM_ID:0x000a50e1,OEM_ID:0x0051,MODEL_ID:0x4985)
PK_HASH:           0x2acf3a85fde334e2e28d64cbc416b2474e0e95cad4698f143e27479d67e92d99
Serial:            0x14eedb3c
SBL Version:       0x00000000

Detected loader: Loaders\000a50e100514985_2acf3a85fde334e2_FHPRG.bin
Successfully uploaded programmer :)
Binary build date: Aug 20 2019 @ 10:45:48
Binary build date: Aug 20 2019 @ 10:45:48
Chip serial num: 351198012 (0x14eedb3c)
Supported Functions (21):
program
read
nop
patch
configure
setbootablestoragedrive
erase
power
firmwarewrite
getstorageinfo
benchmark
emmc
ufs
fixgpt
getsha256digest
gethwversion
getrfversion
getprjversion
setprojmodel
sha256init
sha256final
End of supported functions 21
TargetName=Unknown
MemoryName=UFS
Version=1
Traceback (most recent call last):
  File "edl.py", line 419, in <module>
    main()
  File "edl.py", line 215, in main
    data = fh.cmd_read_buffer(args.lun, 0, 0x4000 // cfg.SECTOR_SIZE_IN_BYTES,False)
  File "C:\Users\y2k\Desktop\edl\Library\firehose.py", line 265, in cmd_read_buffer
    rsp=self.xml.getresponse(self.cdc.read(self.cfg.MaxXMLSizeInBytes))
  File "C:\Users\y2k\Desktop\edl\Library\usb.py", line 67, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "C:\Users\y2k\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\core.py", line 988, in read
    self.__get_timeout(timeout))
  File "C:\Users\y2k\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\backend\libusb0.py", line 542, in bulk_read
    timeout)
  File "C:\Users\y2k\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\backend\libusb0.py", line 627, in __read
    timeout
  File "C:\Users\y2k\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\backend\libusb0.py", line 431, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'
```
Any assistance would be appreciated. Thanks!

**Comment by bkerler** [comment]
Hi, this could have several reasons. One might be that the loader isn't matching the hw init. Another could be libusb driver issue. Please test the latest commit to see if this issue has been fixed for you. Thanks !

**Comment by bkerler** [comment]
Oh and you need to give the right lun for ufs :)

**Comment by bkerler** [comment]
The oneplus 7 and above have secure edl implementation, that's why ;)

**Comment by shuvragood** [comment]
Please do compare both. Might be the issue can be identified with USB Time out error .
I am having all code with me (https://drive.google.com/drive/folders/1hKyy2O2HLyh9o4wxKsPFoyXOMyaorkv7)

https://www.duo.uio.no/bitstream/handle/10852/82665/5/Olav-Bjerke---masteroppgave.pdf .


Getting USB Time out error while replicating this into CY8CKIT-059
