### ISSUE TITLE
Unable to communicate with Sierra EM7455

### ISSUE THREAD

**Issue by Leo-PL** [bkerler/edl#602]
A few years ago, using v3.4 I managed to dump an EM7455. However, using current master I'm greeted with a sahara error immediately after module enters bootloader:
```
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Using loader ../../sierra_em7455/NPRG9x35px.bin ...
main - Waiting for the device
DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold vol dwn + pwr, in fastboot mode connect usb.
        Run "./fastpwn oem edl".
main - Other:  Run "adb reboot edl".

DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.
DeviceClass
DeviceClass - [LIB]: Couldn't detect the device. Is it connected ?
.DeviceClass
DeviceClass - [LIB]: Detaching kernel driver
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: ['  File "/home/lechu/devel/edl/edl", line 393, in <module>\n    base.run()\n', '  File "/home/lechu/devel/edl/edl", line 290, in run\n    conninfo = self.doconnect(loop)\n', '  File "/home/lechu/devel/edl/edl", line 222, in doconnect\n    resp = self.sahara.connect()\n']
DeviceClass
DeviceClass - [LIB]: TX:<?xml version="1.0" ?><data><nop /></data>
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: ['  File "/home/lechu/devel/edl/edl", line 393, in <module>\n    base.run()\n', '  File "/home/lechu/devel/edl/edl", line 290, in run\n    conninfo = self.doconnect(loop)\n', '  File "/home/lechu/devel/edl/edl", line 222, in doconnect\n    resp = self.sahara.connect()\n']
DeviceClass
DeviceClass - [LIB]: TX:7e11001200a0e30000c1e50140a0e31eff2fe14bd97e
DeviceClass
DeviceClass - [LIB]: read:0xa
DeviceClass
DeviceClass - [LIB]: ['  File "/home/lechu/devel/edl/edl", line 393, in <module>\n    base.run()\n', '  File "/home/lechu/devel/edl/edl", line 290, in run\n    conninfo = self.doconnect(loop)\n', '  File "/home/lechu/devel/edl/edl", line 222, in doconnect\n    resp = self.sahara.connect()\n', '  File "/home/lechu/devel/edl/edlclient/Library/sahara.py", line 148, in connect\n    res = self.cdc.read()\n']
DeviceClass
DeviceClass - [LIB]: RX:7e0d1600000000884d7e
main - Mode detected: error
Connection detected, quiting.
```
Any idea what was changed, that might have broken it? Same now happens with EM7455, too.
Anything that might poke with the QDLoader port was stopped, just in case.

I tried going back to v3.4, and even set up Debian Bullseye and Buster in chroot, to get it going - it enters nandprg mode correctly, but loading still fails anyway, probably due to changes in some unpinned dependency which changed API:
```
Qualcomm Sahara / Firehose Client V3.4 (c) B.Kerler 2018-2021.
main - Using loader ../NPRG9x35px.bin ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold Vol up + pwr, in fastboot mode connect usb.
        Run "./fastboot oem edl".
main - Other:  Run "adb reboot edl".

...............
...main - Device detected :)
main - Mode detected: nandprg
Traceback (most recent call last):
  File "./edl.py", line 368, in <module>
    base.run()
  File "./edl.py", line 359, in run
    sc.handle_streaming(cmd, options)
  File "/root/edl/Library/streaming_client.py", line 79, in handle_streaming
    if self.streaming.connect(mode):
  File "/root/edl/Library/streaming.py", line 751, in connect
    i = resp[1]
TypeError: 'int' object is not subscriptable
```

I'd be glad for any pointer where to start looking - maybe I could devise the fix once I know what's going on.

**Comment by Leo-PL** [comment]
I came to realization that `nandprg` isn't the right mode before starting loader, so I need to drop the modem one level lower, to `sahara` in another way than plain `AT!BOOTHOLD`. This can be closed - sorry for the noise :-)
