### ISSUE TITLE
Not Implemented - Lenovo CD-18781Y

### ISSUE THREAD

**Issue by Termitebug** [bkerler/edl#603]
When I try this command the result is following:
`PS C:\Users\Kalle\Desktop\edl-master>  ./edl qfil bin/rawprogram.xml bin/patch0.xml flash/ --loader=bin/prog_emmc_firehose_8953_ddr.mbn
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Using loader bin/prog_emmc_firehose_8953_ddr.mbn ...
main - Waiting for the device
Traceback (most recent call last):
  File "C:\Users\Kalle\Desktop\edl-master\edl", line 393, in <module>
    base.run()
  File "C:\Users\Kalle\Desktop\edl-master\edl", line 290, in run
    conninfo = self.doconnect(loop)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalle\Desktop\edl-master\edl", line 202, in doconnect
    self.cdc.connected = self.cdc.connect(portname=self.portname)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalle\Desktop\edl-master\edlclient\Library\Connection\usblib.py", line 241, in connect
    self.configuration = self.device.get_active_configuration()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalle\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\core.py", line 921, in get_active_configuration
    return self._ctx.get_active_configuration(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalle\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalle\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\core.py", line 249, in get_active_configuration
    self.managed_open()
  File "C:\Users\Kalle\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalle\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalle\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalle\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "C:\Users\Kalle\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\backend\libusb1.py", line 600, in _check
    raise NotImplementedError(_strerror(ret))
NotImplementedError: Operation not supported or unimplemented on this platform`

**Comment by Termitebug** [comment]
Had to wice cache partition, install zadig and wipe & factory reset.
https://community.home-assistant.io/t/is-this-the-perfect-standalone-tablet-for-ha/658422/59
