### ISSUE TITLE
error when dumping msm8916 PBL 

### ISSUE THREAD

**Issue by hicode002** [bkerler/edl#609]
My device is unfused.When I use edl pbl pbl.bin,I got an error when the progress was at 75%
Same as https://github.com/bkerler/edl/issues/326

```
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
Version 0x2
------------------------
HWID:              0x007050e100000000 (MSM_ID:0x007050e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "MSM8916"
PK_HASH:           0xcc3153a80293939b90d02d3bf8b23e0292e452fef662c74998421adad42a380f
Serial:            0x1a8f0b45

sahara - Possibly unfused device detected, so any loader should be fine...
sahara - Possible loader available: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/longcheer/007050e100000000_3022817d373fd7f9_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/lyf/007050e100000000_394a2e47cf830150_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/lenovo_motorola/007050e100000000_99c8c13e374c34d8_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/xiaomi/007050e100000000_50838757eab7c632_fhprg_peek_wt88047.bin
sahara - Possible loader available: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/xiaomi/007050e100000000_278448179ac756a1_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/qualcomm/factory/msm8916/007050e100000000_8ecf3eaa03f772e2_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/cyanogen/007050e100000000_4614048173062ae4_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/cyanogen/007050e100000000_d36c6073c9c2cb1c_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/cyanogen/007050e100000000_4e3eefa63a67eb7a_fhprg_peek.bin
sahara - Trying loader: /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/longcheer/007050e100000000_3022817d373fd7f9_fhprg_peek.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/../Loaders/longcheer/007050e100000000_3022817d373fd7f9_fhprg_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: !DEBUG! rsp.data: 'bytearray(b'<?xml version="1.0" encoding="UTF-8" ?><data><log value="logbuf@0x0801BDA8 fh@0x08018C10" /></data>')'
firehose - TargetName=MSM8916
firehose - MemoryName=eMMC
firehose - Version=1
firehose - Trying to read first storage sector...
firehose - Running configure...
firehose_client - Supported functions:
-----------------
firehose - Peek: Address(0x100000),Size(0x1ffb0)
Progress: |██████████████████████████████████████------------|  75.0% Complete                                                                                                                            Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.62', 'edl')
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 393, in <module>
    base.run()
  File "/usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/EGG-INFO/scripts/edl", line 385, in run
    if not fh.handle_firehose(cmd, options):
  File "/usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/Library/firehose_client.py", line 397, in handle_firehose
    if self.firehose.cmd_peek(target_name[0][0], target_name[0][1], filename, True):
  File "/usr/local/lib/python3.10/site-packages/edlclient-3.62-py3.10.egg/edlclient/Library/firehose.py", line 1683, in cmd_peek
    rdata = self.xml.getlog(tmp)[0].replace("0x", "").replace(" ", "")
IndexError: list index out of range

```

**Comment by RenateUSB** [comment]
I would guess that your PBL is not actually as big as indicated in `qualcomm_config.py`

Just fudge that 0x1ffb0 to 0x18000 in that file.
